#### Importaciones

In [2]:
# Importaciones

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Visualización Pandas

In [3]:
# Deslimitar/Limitar display Pandas

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)
pd.set_option('display.max_colwidth', None)

#### Preparación del DF inicial

In [4]:
# Leer Hoteles

df_Hoteles = pd.read_csv(r'D:\DEV\Python\00_TFM_PALLADIUM\02_DATASETS_GENERADOS\Hoteles_std.csv', sep = ';', decimal=',')
df_Hoteles.head(100)

     ID                                       Nombre  America Pais_Hotel
0     0                             HotelDesconocido        0         ND
1     5                      TheRoyalSuitesPuntaMita        1         MX
2     6                            PalladiumVallarta        1         MX
3     9                  DominicanFiestaHotel&Casino        1         RD
4    12                      PalladiumHotelDonCarlos        0         ES
5    14                       MallorcaRocksBuilding1        0         ES
6    15                       UshuaiaIbizaBeachHotel        0         ES
7    16                      MallorcaRocksApartments        0         ES
8    17                          FiestaClubPalmBeach        0         ES
9    19                          AgroturismoSaTalaia        0         ES
10   20                     PalladiumHotelCalaLlonga        0         ES
11   21                          FiestaHotelCalaNova        0         ES
12   22                        PalladiumHotelPalmyra        0         ES
13   23                            FiestaHotelMilord        0         ES
14   24                            FiestaClubDonToni        0         ES
15   25                             FiestaHotelTanit        0         ES
16   26                       MallorcaRocksBuilding2        0         ES
17   27                        FiestaHotelCalaGracio        0         ES
18   28                           FiestaHotelDonToni        0         ES
19   30                           HardRockHotelIbiza        0         ES
20   31                      FiestaHotelCastellPlaya        0         ES
21   32                        HardRockHotelTenerife        0         ES
22   83             GrandPalladiumImbassaiResort&Spa        1         BR
23   92     GrandPalladiumJamaica&LadyHamiltonResort        1         JK
24   94  GrandPalladiumPalaceIbiza&WhiteIslandResort        0         ES
25   96                         ComplejoCostaMujeres        1         MX
26   97                           BlessHotelMadrid5*        0         ES
27   98                    PalladiumHotelCostadelSol        0         ES
28   99                                   TRSCapCana        1         RD
29  100                              BlessHotelIbiza        0         ES
30  102                        PalladiumHotelMenorca        0         ES
31  103              GrandPalladiumSiciliaResort&Spa        0         IT
32  106                          ComplejoRivieraMaya        1         MX
33  107                            ComplejoPuntaCana        1         RD
34  110                                TRSIbizaHotel        0         ES

In [5]:
# Filtrar por sólo hoteles de América

df_Hoteles_America = df_Hoteles.loc[df_Hoteles['America'] == 1].reset_index(drop=True)
df_Hoteles_America = df_Hoteles_America.drop(columns = 'America')
print(f'Trabajaremos con {len(df_Hoteles_America)} hoteles')
df_Hoteles_America

Trabajaremos con 9 hoteles

    ID                                    Nombre Pais_Hotel
0    5                   TheRoyalSuitesPuntaMita         MX
1    6                         PalladiumVallarta         MX
2    9               DominicanFiestaHotel&Casino         RD
3   83          GrandPalladiumImbassaiResort&Spa         BR
4   92  GrandPalladiumJamaica&LadyHamiltonResort         JK
5   96                      ComplejoCostaMujeres         MX
6   99                                TRSCapCana         RD
7  106                       ComplejoRivieraMaya         MX
8  107                         ComplejoPuntaCana         RD

In [6]:
# Tienen sentido los tipos de datos? -> Sí

df_Hoteles_America.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          9 non-null      int64
 1   Nombre      9 non-null      object
 2   Pais_Hotel  9 non-null      object
dtypes: int64(1), object(2)
memory usage: 348.0+ bytes

In [7]:
df_Reservas = pd.read_csv(r'D:\DEV\Python\00_TFM_PALLADIUM\02_DATASETS_GENERADOS\Reservas_22_23_std.csv', sep = ';', decimal='.')
df_Reservas.head()

,ID_RESERVA,ID_HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
0,484750709201,92,2022-07-0500:00:00.000,2022-07-1100:00:00.000,6,AllInclusive,37000,JAMJuniorSuiteOFV,2,4,3,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,9,0,0,0,0,2022-05-2200:00:00.000,2022-05-3000:00:00.000,NaN,0,NaN,1460.70,798.00,0.0,0.00,0,1460.70,798.00,0.0,1,0,CANADA,Fixedrates,DIRECTSALES
1,456094009201,92,2022-12-2800:00:00.000,2023-01-0400:00:00.000,7,AllInclusive,23300,LHAmbassadorSuiteBSOV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,1,0,60444109200,0,0,2022-01-1300:00:00.000,2022-12-2800:00:00.000,NaN,0,NaN,1868.00,708.00,0.0,0.00,0,1868.00,708.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES
2,425835909201,92,2022-01-2200:00:00.000,2022-01-2900:00:00.000,7,AllInclusive,43800,LHJuniorSuiteGV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2021-07-1300:00:00.000,2022-01-2000:00:00.000,2022-01-2000:00:00.000,0,NaN,1329.30,665.00,0.0,0.00,0,1329.30,665.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES
3,549929510601,106,2023-11-0600:00:00.000,2023-11-1400:00:00.000,8,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2023-04-1700:00:00.000,2023-11-0704:27:02.000,2023-10-1700:00:00.000,0,NaN,1146.56,1146.56,0.0,12.48,0,1146.56,1146.56,0.0,1,0,CANADA,Fixedrates,DIRECTSALES
4,519229110601,106,2023-11-0600:00:00.000,2023-11-2300:00:00.000,17,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2023-02-2212:48:29.000,2023-11-0704:27:15.000,2023-09-1400:00:00.000,0,NaN,2436.44,2436.44,0.0,26.52,0,2436.44,2436.44,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES

In [8]:
# Tienen sentido los tipos de datos? -> No todos

df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337983 entries, 0 to 1337982
Data columns (total 42 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337983 non-null  int64
 1   ID_HOTEL           1337983 non-null  int64
 2   LLEGADA            1337983 non-null  object
 3   SALIDA             1337983 non-null  object
 4   NOCHES             1337983 non-null  int64
 5   REGIMEN            1337966 non-null  object
 6   ID_TIPO            1337983 non-null  int64
 7   TIPO               1337983 non-null  object
 8   USO                1337983 non-null  int64
 9   PAX                1337983 non-null  int64
 10  ADULTOS            1337983 non-null  int64
 11  NENES              1337983 non-null  int64
 12  BEBES              1337983 non-null  int64
 13  ID_CLIENTE         1337983 non-null  int64
 14  TIPO_CLIENTE       1337983 non-null  int64
 15  CLIENTE            1337975 non-null  object
 16  ID_MULTIPLE        1337983 non-null  int64
 17  ID_MONEDA          1337983 non-null  int64
 18  MONEDA             1337983 non-null  object
 19  STATUS             1337983 non-null  int64
 20  ID_MOTIVO          1337983 non-null  int64
 21  ID_CARDEX          1337983 non-null  int64
 22  SUPLETORIA         1337983 non-null  int64
 23  CUNAS              1337983 non-null  int64
 24  FECHA_TOMA         1337983 non-null  object
 25  FECHA_MOD          1337703 non-null  object
 26  FECHA_CANCELACION  438588 non-null   object
 27  ID_FIDELIDAD       1337983 non-null  int64
 28  FIDELIDAD          211029 non-null   object
 29  VALHAB             1337983 non-null  float64
 30  VALPEN             1337983 non-null  float64
 31  VALSERV            1337983 non-null  float64
 32  VALFIJOS           1337983 non-null  float64
 33  COMERCIALIZADORA   1337983 non-null  int64
 34  CMVALHAB           1337983 non-null  float64
 35  CMVALPEN           1337983 non-null  float64
 36  CMCVALSERV         1337983 non-null  float64
 37  AUTORIZO           1337983 non-null  int64
 38  GRATIS             1337983 non-null  int64
 39  PAIS               1337983 non-null  object
 40  SEGMENTO           1337983 non-null  object
 41  FUENTE_NEGOCIO     1337983 non-null  object
dtypes: float64(7), int64(22), object(13)
memory usage: 428.7+ MB

In [9]:
# Antes de nada, introducimos los nombres de los hoteles con merge a df_Hoteles_America, si generase nans, habría que dropearlos para no trabajar con hoteles de fuera de América:
df_Reservas = df_Reservas.merge(
    df_Hoteles[['ID', 'Nombre']].rename(columns={'Nombre': 'HOTEL'}),
    left_on='ID_HOTEL',
    right_on='ID',
    how='left'
).drop(columns='ID')

In [10]:
df_Reservas.head()

,ID_RESERVA,ID_HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,HOTEL
0,484750709201,92,2022-07-0500:00:00.000,2022-07-1100:00:00.000,6,AllInclusive,37000,JAMJuniorSuiteOFV,2,4,3,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,9,0,0,0,0,2022-05-2200:00:00.000,2022-05-3000:00:00.000,NaN,0,NaN,1460.70,798.00,0.0,0.00,0,1460.70,798.00,0.0,1,0,CANADA,Fixedrates,DIRECTSALES,GrandPalladiumJamaica&LadyHamiltonResort
1,456094009201,92,2022-12-2800:00:00.000,2023-01-0400:00:00.000,7,AllInclusive,23300,LHAmbassadorSuiteBSOV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,1,0,60444109200,0,0,2022-01-1300:00:00.000,2022-12-2800:00:00.000,NaN,0,NaN,1868.00,708.00,0.0,0.00,0,1868.00,708.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,GrandPalladiumJamaica&LadyHamiltonResort
2,425835909201,92,2022-01-2200:00:00.000,2022-01-2900:00:00.000,7,AllInclusive,43800,LHJuniorSuiteGV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2021-07-1300:00:00.000,2022-01-2000:00:00.000,2022-01-2000:00:00.000,0,NaN,1329.30,665.00,0.0,0.00,0,1329.30,665.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,GrandPalladiumJamaica&LadyHamiltonResort
3,549929510601,106,2023-11-0600:00:00.000,2023-11-1400:00:00.000,8,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2023-04-1700:00:00.000,2023-11-0704:27:02.000,2023-10-1700:00:00.000,0,NaN,1146.56,1146.56,0.0,12.48,0,1146.56,1146.56,0.0,1,0,CANADA,Fixedrates,DIRECTSALES,ComplejoRivieraMaya
4,519229110601,106,2023-11-0600:00:00.000,2023-11-2300:00:00.000,17,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2023-02-2212:48:29.000,2023-11-0704:27:15.000,2023-09-1400:00:00.000,0,NaN,2436.44,2436.44,0.0,26.52,0,2436.44,2436.44,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,ComplejoRivieraMaya

In [11]:
df_Reservas.columns

Index(['ID_RESERVA', 'ID_HOTEL', 'LLEGADA', 'SALIDA', 'NOCHES', 'REGIMEN',
       'ID_TIPO', 'TIPO', 'USO', 'PAX', 'ADULTOS', 'NENES', 'BEBES',
       'ID_CLIENTE', 'TIPO_CLIENTE', 'CLIENTE', 'ID_MULTIPLE', 'ID_MONEDA',
       'MONEDA', 'STATUS', 'ID_MOTIVO', 'ID_CARDEX', 'SUPLETORIA', 'CUNAS',
       'FECHA_TOMA', 'FECHA_MOD', 'FECHA_CANCELACION', 'ID_FIDELIDAD',
       'FIDELIDAD', 'VALHAB', 'VALPEN', 'VALSERV', 'VALFIJOS',
       'COMERCIALIZADORA', 'CMVALHAB', 'CMVALPEN', 'CMCVALSERV', 'AUTORIZO',
       'GRATIS', 'PAIS', 'SEGMENTO', 'FUENTE_NEGOCIO', 'HOTEL'],
      dtype='object')

In [12]:
df_Reservas = df_Reservas[['ID_RESERVA', 'ID_HOTEL', 'HOTEL', 'LLEGADA', 'SALIDA', 'NOCHES', 'REGIMEN',
       'ID_TIPO', 'TIPO', 'USO', 'PAX', 'ADULTOS', 'NENES', 'BEBES',
       'ID_CLIENTE', 'TIPO_CLIENTE', 'CLIENTE', 'ID_MULTIPLE', 'ID_MONEDA',
       'MONEDA', 'STATUS', 'ID_MOTIVO', 'ID_CARDEX', 'SUPLETORIA', 'CUNAS',
       'FECHA_TOMA', 'FECHA_MOD', 'FECHA_CANCELACION', 'ID_FIDELIDAD',
       'FIDELIDAD', 'VALHAB', 'VALPEN', 'VALSERV', 'VALFIJOS',
       'COMERCIALIZADORA', 'CMVALHAB', 'CMVALPEN', 'CMCVALSERV', 'AUTORIZO',
       'GRATIS', 'PAIS', 'SEGMENTO', 'FUENTE_NEGOCIO']]

In [13]:
df_Reservas.head()

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
0,484750709201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-07-0500:00:00.000,2022-07-1100:00:00.000,6,AllInclusive,37000,JAMJuniorSuiteOFV,2,4,3,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,9,0,0,0,0,2022-05-2200:00:00.000,2022-05-3000:00:00.000,NaN,0,NaN,1460.70,798.00,0.0,0.00,0,1460.70,798.00,0.0,1,0,CANADA,Fixedrates,DIRECTSALES
1,456094009201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-12-2800:00:00.000,2023-01-0400:00:00.000,7,AllInclusive,23300,LHAmbassadorSuiteBSOV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,1,0,60444109200,0,0,2022-01-1300:00:00.000,2022-12-2800:00:00.000,NaN,0,NaN,1868.00,708.00,0.0,0.00,0,1868.00,708.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES
2,425835909201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-01-2200:00:00.000,2022-01-2900:00:00.000,7,AllInclusive,43800,LHJuniorSuiteGV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2021-07-1300:00:00.000,2022-01-2000:00:00.000,2022-01-2000:00:00.000,0,NaN,1329.30,665.00,0.0,0.00,0,1329.30,665.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES
3,549929510601,106,ComplejoRivieraMaya,2023-11-0600:00:00.000,2023-11-1400:00:00.000,8,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2023-04-1700:00:00.000,2023-11-0704:27:02.000,2023-10-1700:00:00.000,0,NaN,1146.56,1146.56,0.0,12.48,0,1146.56,1146.56,0.0,1,0,CANADA,Fixedrates,DIRECTSALES
4,519229110601,106,ComplejoRivieraMaya,2023-11-0600:00:00.000,2023-11-2300:00:00.000,17,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2023-02-2212:48:29.000,2023-11-0704:27:15.000,2023-09-1400:00:00.000,0,NaN,2436.44,2436.44,0.0,26.52,0,2436.44,2436.44,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES

In [14]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337983 entries, 0 to 1337982
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337983 non-null  int64
 1   ID_HOTEL           1337983 non-null  int64
 2   HOTEL              1337968 non-null  object
 3   LLEGADA            1337983 non-null  object
 4   SALIDA             1337983 non-null  object
 5   NOCHES             1337983 non-null  int64
 6   REGIMEN            1337966 non-null  object
 7   ID_TIPO            1337983 non-null  int64
 8   TIPO               1337983 non-null  object
 9   USO                1337983 non-null  int64
 10  PAX                1337983 non-null  int64
 11  ADULTOS            1337983 non-null  int64
 12  NENES              1337983 non-null  int64
 13  BEBES              1337983 non-null  int64
 14  ID_CLIENTE         1337983 non-null  int64
 15  TIPO_CLIENTE       1337983 non-null  int64
 16  CLIENTE            1337975 non-null  object
 17  ID_MULTIPLE        1337983 non-null  int64
 18  ID_MONEDA          1337983 non-null  int64
 19  MONEDA             1337983 non-null  object
 20  STATUS             1337983 non-null  int64
 21  ID_MOTIVO          1337983 non-null  int64
 22  ID_CARDEX          1337983 non-null  int64
 23  SUPLETORIA         1337983 non-null  int64
 24  CUNAS              1337983 non-null  int64
 25  FECHA_TOMA         1337983 non-null  object
 26  FECHA_MOD          1337703 non-null  object
 27  FECHA_CANCELACION  438588 non-null   object
 28  ID_FIDELIDAD       1337983 non-null  int64
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337983 non-null  float64
 31  VALPEN             1337983 non-null  float64
 32  VALSERV            1337983 non-null  float64
 33  VALFIJOS           1337983 non-null  float64
 34  COMERCIALIZADORA   1337983 non-null  int64
 35  CMVALHAB           1337983 non-null  float64
 36  CMVALPEN           1337983 non-null  float64
 37  CMCVALSERV         1337983 non-null  float64
 38  AUTORIZO           1337983 non-null  int64
 39  GRATIS             1337983 non-null  int64
 40  PAIS               1337983 non-null  object
 41  SEGMENTO           1337983 non-null  object
 42  FUENTE_NEGOCIO     1337983 non-null  object
dtypes: float64(7), int64(22), object(14)
memory usage: 438.9+ MB

#### EDA Preliminar

In [15]:
# Antes de nada
# Los IDs, aunque sean números, no implican cardinalidad
# Los pasaremos todos a object, junto con las demás columnas que tengan sentido

cat_cols = [['ID_RESERVA',
             'ID_HOTEL',
             'HOTEL',
             'REGIMEN',
             'ID_TIPO',
             'TIPO',
             'ID_CLIENTE',
             'TIPO_CLIENTE',
             'CLIENTE',
             'ID_MONEDA',
             'MONEDA',
             'STATUS',
             'ID_MOTIVO',
             'ID_CARDEX',
             'ID_FIDELIDAD',
             'FIDELIDAD',
             'PAIS',
             'SEGMENTO',
             'FUENTE_NEGOCIO']]

for col in cat_cols:
    df_Reservas[col] = df_Reservas[col].astype('object')

In [16]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337983 entries, 0 to 1337982
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337983 non-null  object
 1   ID_HOTEL           1337983 non-null  object
 2   HOTEL              1337968 non-null  object
 3   LLEGADA            1337983 non-null  object
 4   SALIDA             1337983 non-null  object
 5   NOCHES             1337983 non-null  int64
 6   REGIMEN            1337966 non-null  object
 7   ID_TIPO            1337983 non-null  object
 8   TIPO               1337983 non-null  object
 9   USO                1337983 non-null  int64
 10  PAX                1337983 non-null  int64
 11  ADULTOS            1337983 non-null  int64
 12  NENES              1337983 non-null  int64
 13  BEBES              1337983 non-null  int64
 14  ID_CLIENTE         1337983 non-null  object
 15  TIPO_CLIENTE       1337983 non-null  object
 16  CLIENTE            1337975 non-null  object
 17  ID_MULTIPLE        1337983 non-null  int64
 18  ID_MONEDA          1337983 non-null  object
 19  MONEDA             1337983 non-null  object
 20  STATUS             1337983 non-null  object
 21  ID_MOTIVO          1337983 non-null  object
 22  ID_CARDEX          1337983 non-null  object
 23  SUPLETORIA         1337983 non-null  int64
 24  CUNAS              1337983 non-null  int64
 25  FECHA_TOMA         1337983 non-null  object
 26  FECHA_MOD          1337703 non-null  object
 27  FECHA_CANCELACION  438588 non-null   object
 28  ID_FIDELIDAD       1337983 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337983 non-null  float64
 31  VALPEN             1337983 non-null  float64
 32  VALSERV            1337983 non-null  float64
 33  VALFIJOS           1337983 non-null  float64
 34  COMERCIALIZADORA   1337983 non-null  int64
 35  CMVALHAB           1337983 non-null  float64
 36  CMVALPEN           1337983 non-null  float64
 37  CMCVALSERV         1337983 non-null  float64
 38  AUTORIZO           1337983 non-null  int64
 39  GRATIS             1337983 non-null  int64
 40  PAIS               1337983 non-null  object
 41  SEGMENTO           1337983 non-null  object
 42  FUENTE_NEGOCIO     1337983 non-null  object
dtypes: float64(7), int64(12), object(24)
memory usage: 438.9+ MB

#### HOTEL

In [17]:
# Vamos a ver si los NANs en hoteles nos dan alguna pista sobre de qué hotel puede tratarse o si son errores tipográficos en el ID

df_Reservas.loc[df_Reservas['HOTEL'].isna()]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
13930,359046409101,91,NaN,2023-05-1500:00:00.000,2023-05-2900:00:00.000,14,AllInclusive,33500,BAVSuperiorJSGV,2,2,2,0,0,19530901,1,THOMSONGROUP/TUIUKLTD,0,700,Dolar,3,119100,0,0,0,2020-01-2400:00:00.000,2022-07-1400:00:00.000,2022-07-1400:00:00.000,0,NaN,1531.04,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,REINOUNIDO,FixedRates,T.O./T.A.
40572,350677100301,3,NaN,2022-08-2000:00:00.000,2022-08-3100:00:00.000,11,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,19530901,1,THOMSONGROUP/TUIUKLTD,0,700,Dolar,1,0,0,0,0,2019-11-2900:00:00.000,2021-09-1000:00:00.000,NaN,0,NaN,1474.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,REINOUNIDO,FixedRates,T.O./T.A.
145580,374900608501,85,NaN,2022-04-1900:00:00.000,2022-04-2600:00:00.000,7,AllInclusive,13100,COLRomanceVillaSuite,1,1,1,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,Dolar,1,0,0,0,0,2020-07-0500:00:00.000,NaN,NaN,0,NaN,2585.73,0.0,0.0,8.12,0,2585.73,0.0,0.0,0,0,ESTADOSUNIDOS,Package,DIRECTSALES
390938,347263900301,3,NaN,2022-10-1300:00:00.000,2022-10-2700:00:00.000,14,AllInclusive,25800,TRSJuniorSuitePPGV,2,2,2,0,0,19530901,1,THOMSONGROUP/TUIUKLTD,0,700,Dolar,3,119100,0,0,0,2019-11-1100:00:00.000,2021-12-1300:00:00.000,2021-12-1300:00:00.000,0,NaN,1876.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,REINOUNIDO,FixedRates,T.O./T.A.
572056,375627300301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
572057,375627400301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
572058,375627500301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
572059,375627100301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
572060,375627800301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
572061,375627700301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
572062,375628000301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
572063,375627900301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
796728,345471600301,3,NaN,2022-10-0700:00:00.000,2022-10-2100:00:00.000,14,AllInclusive,26400,TRSSuitePPGV,2,2,2,0,0,19530901,1,THOMSONGROUP/TUIUKLTD,0,700,Dolar,3,119000,0,0,0,2019-10-2800:00:00.000,2022-09-3000:00:00.000,2022-09-3000:00:00.000,0,NaN,2436.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,REINOUNIDO,FixedRates,T.O./T.A.
1305060,375627600301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
1305061,375627200301,3,NaN,2022-04-2300:00:00.000,2022-04-3000:00:00.000,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,20769905,1,APPLEVACATIONSTMTC,375627000301,700,Dolar,3,119100,0,0,0,2020-07-1700:00:00.000,2021-10-1800:00:00.000,2021-10-1800:00:00.000,0,NaN,938.00,0.0,0.0,0.00,1,0.00,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.

In [18]:
# Vemos que no, son IDs que, no es que no sean americanos, sino que directamente no están en la lista de hoteles facilitada en los datos de estudio, así que eliminamos dichas filas:

df_Reservas = df_Reservas.dropna(subset=['HOTEL'])

In [19]:
# La relación entre ID_HOTEL y HOTEL ovbiamente va a ser 1:1, pues acabamos de hacerle un merge, así que nada que comprobar por ahí

In [20]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337968 entries, 0 to 1337982
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337968 non-null  object
 1   ID_HOTEL           1337968 non-null  object
 2   HOTEL              1337968 non-null  object
 3   LLEGADA            1337968 non-null  object
 4   SALIDA             1337968 non-null  object
 5   NOCHES             1337968 non-null  int64
 6   REGIMEN            1337951 non-null  object
 7   ID_TIPO            1337968 non-null  object
 8   TIPO               1337968 non-null  object
 9   USO                1337968 non-null  int64
 10  PAX                1337968 non-null  int64
 11  ADULTOS            1337968 non-null  int64
 12  NENES              1337968 non-null  int64
 13  BEBES              1337968 non-null  int64
 14  ID_CLIENTE         1337968 non-null  object
 15  TIPO_CLIENTE       1337968 non-null  object
 16  CLIENTE            1337960 non-null  object
 17  ID_MULTIPLE        1337968 non-null  int64
 18  ID_MONEDA          1337968 non-null  object
 19  MONEDA             1337968 non-null  object
 20  STATUS             1337968 non-null  object
 21  ID_MOTIVO          1337968 non-null  object
 22  ID_CARDEX          1337968 non-null  object
 23  SUPLETORIA         1337968 non-null  int64
 24  CUNAS              1337968 non-null  int64
 25  FECHA_TOMA         1337968 non-null  object
 26  FECHA_MOD          1337689 non-null  object
 27  FECHA_CANCELACION  438575 non-null   object
 28  ID_FIDELIDAD       1337968 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337968 non-null  float64
 31  VALPEN             1337968 non-null  float64
 32  VALSERV            1337968 non-null  float64
 33  VALFIJOS           1337968 non-null  float64
 34  COMERCIALIZADORA   1337968 non-null  int64
 35  CMVALHAB           1337968 non-null  float64
 36  CMVALPEN           1337968 non-null  float64
 37  CMCVALSERV         1337968 non-null  float64
 38  AUTORIZO           1337968 non-null  int64
 39  GRATIS             1337968 non-null  int64
 40  PAIS               1337968 non-null  object
 41  SEGMENTO           1337968 non-null  object
 42  FUENTE_NEGOCIO     1337968 non-null  object
dtypes: float64(7), int64(12), object(24)
memory usage: 449.1+ MB

#### LLEGADA, SALIDA, NOCHES

In [21]:
# Vamos a comprobar si las horas de llegada son todo 0 o hay variedad, porque a priori parece que no la hay. Si es todo 0 no aportaría nada a nuestro modelo

df_Reservas['LLEGADA'].str[10:].unique()

array(['00:00:00.000'], dtype=object)

In [22]:
# Todo 0, así que recortamos los caracteres a LLEGADA para quedarme sólo con la fecha
df_Reservas['LLEGADA'] = df_Reservas['LLEGADA'].str[:10]

In [23]:
# Ídem SALIDA
df_Reservas['SALIDA'].str[10:].unique()

array(['00:00:00.000'], dtype=object)

In [24]:
# Ídem SALIDA
df_Reservas['SALIDA'] = df_Reservas['SALIDA'].str[:10]

In [25]:
# Pasamos ambas a formato fecha

df_Reservas['LLEGADA'] = pd.to_datetime(df_Reservas['LLEGADA'], format='%Y-%m-%d')
df_Reservas['SALIDA'] = pd.to_datetime(df_Reservas['SALIDA'], format='%Y-%m-%d')

In [26]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337968 entries, 0 to 1337982
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337968 non-null  object
 1   ID_HOTEL           1337968 non-null  object
 2   HOTEL              1337968 non-null  object
 3   LLEGADA            1337968 non-null  datetime64[ns]
 4   SALIDA             1337968 non-null  datetime64[ns]
 5   NOCHES             1337968 non-null  int64
 6   REGIMEN            1337951 non-null  object
 7   ID_TIPO            1337968 non-null  object
 8   TIPO               1337968 non-null  object
 9   USO                1337968 non-null  int64
 10  PAX                1337968 non-null  int64
 11  ADULTOS            1337968 non-null  int64
 12  NENES              1337968 non-null  int64
 13  BEBES              1337968 non-null  int64
 14  ID_CLIENTE         1337968 non-null  object
 15  TIPO_CLIENTE       1337968 non-null  object
 16  CLIENTE            1337960 non-null  object
 17  ID_MULTIPLE        1337968 non-null  int64
 18  ID_MONEDA          1337968 non-null  object
 19  MONEDA             1337968 non-null  object
 20  STATUS             1337968 non-null  object
 21  ID_MOTIVO          1337968 non-null  object
 22  ID_CARDEX          1337968 non-null  object
 23  SUPLETORIA         1337968 non-null  int64
 24  CUNAS              1337968 non-null  int64
 25  FECHA_TOMA         1337968 non-null  object
 26  FECHA_MOD          1337689 non-null  object
 27  FECHA_CANCELACION  438575 non-null   object
 28  ID_FIDELIDAD       1337968 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337968 non-null  float64
 31  VALPEN             1337968 non-null  float64
 32  VALSERV            1337968 non-null  float64
 33  VALFIJOS           1337968 non-null  float64
 34  COMERCIALIZADORA   1337968 non-null  int64
 35  CMVALHAB           1337968 non-null  float64
 36  CMVALPEN           1337968 non-null  float64
 37  CMCVALSERV         1337968 non-null  float64
 38  AUTORIZO           1337968 non-null  int64
 39  GRATIS             1337968 non-null  int64
 40  PAIS               1337968 non-null  object
 41  SEGMENTO           1337968 non-null  object
 42  FUENTE_NEGOCIO     1337968 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(12), object(22)
memory usage: 449.1+ MB

In [27]:
# Por si acaso, comprobamos que salida - llegada = noches
(df_Reservas['SALIDA']-df_Reservas['LLEGADA']).unique()
# Antes de compararlo con la columna NOCHES ya vemos algo raro... más de 1000 días de diferencia entre entrada y salida? Veamos qué está pasando

<TimedeltaArray>
[   '6 days',    '7 days',    '8 days',   '17 days',   '14 days',   '16 days',
    '4 days',    '2 days',    '5 days',    '9 days',    '3 days',    '1 days',
   '10 days',   '12 days',   '19 days',   '11 days',   '21 days',   '15 days',
   '13 days',   '27 days',    '0 days',   '18 days',   '20 days',   '30 days',
   '45 days',   '38 days',   '25 days',   '28 days',   '29 days',   '35 days',
   '23 days',   '24 days',   '22 days',   '32 days', '1101 days',   '56 days',
   '40 days',   '31 days',   '26 days',   '43 days',   '49 days',   '33 days',
   '65 days',   '36 days', '1102 days',   '62 days',  '145 days',   '37 days',
   '34 days',   '70 days',   '69 days',   '44 days',   '42 days',   '41 days',
   '46 days',   '60 days',   '55 days',   '84 days',   '57 days', '1827 days',
  '247 days',   '52 days',   '39 days',   '61 days',   '48 days',  '370 days',
   '74 days',  '113 days',   '67 days',   '93 days',   '64 days',   '77 days',
  '123 days',   '59 days',  '275 days',   '58 days',   '47 days']
Length: 77, dtype: timedelta64[ns]

In [28]:
# Tras consultar con Palladium, se trata de errores
# El usuario eligió mal el año de salida, con lo que canceló y volvió a reservar
# Dropeamos estos casos para no contaminar el aprendizaje del modelo
# Revisaremos tanto fechas de llegada como de salida

In [29]:
# LLEGADA

# La llegada más temprana
print(min(df_Reservas['LLEGADA']))
# Todo ok

# La llegada más tardía
print(max(df_Reservas['LLEGADA']))
# Vemos que, al menos una persona llega la nochevieja de 2023. Daremos algo de margen antrandop en 2024 para salidas de estos casos

2022-01-01 00:00:00
2023-12-31 00:00:00

In [30]:
# SALIDA

# La salida más temprana
print(min(df_Reservas['SALIDA']))
# Todo ok

# La salida más tardía
print(max(df_Reservas['SALIDA']))
# Problema, veamos

2022-01-02 00:00:00
2028-11-11 00:00:00

In [31]:
# Además, observamos las siguientes discordancias entre noches y la cuenta entre llegada y salida
((df_Reservas['SALIDA'] - df_Reservas['LLEGADA']).dt.days.astype('int64') - df_Reservas['NOCHES']).value_counts(dropna=False)

 0       1337961
 1             3
 3             2
 1645          1
-1             1
Name: count, dtype: int64

In [32]:
# Imputaremos a NOCHES dicha diferencia, pues serían las variables primarias, siendo NOCHEs variable calculada
df_Reservas['NOCHES'] = (df_Reservas['SALIDA'] - df_Reservas['LLEGADA']).dt.days.astype('int64')

In [33]:
#  Vemos que tendría cierto sentido dropear todos hasta el 28º incluido que, además, están todos en status 3 = cancelado
df_Reservas.sort_values("SALIDA", ascending = False).reset_index(drop=True).head(30)

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
0,2754710088011,106,ComplejoRivieraMaya,2023-11-11,2028-11-11,1827,AllInclusive,38600,WSJuniorSuiteGV,2,2,2,0,0,19530901,1,THOMSONGROUP/TUIUKLTD,0,700,Dolar,3,119000,0,0,0,2021-09-0200:00:00.000,2023-11-1205:04:41.000,2021-09-0200:00:00.000,0,NaN,17108.00,0.00,0.0,0.0,1,0.00,0.00,0.0,1,0,REINOUNIDO,FixedRates,T.O./T.A.
1,533495300901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
2,533501200901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
3,533500400901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
4,533499300901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
5,533490600901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
6,533494500901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
7,533496400901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
8,533497600901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
9,533493700901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
10,533499200901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
11,533496900901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
12,533498100901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
13,533497000901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
14,533490200901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
15,533489800901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
16,533498200901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
17,533490800901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
18,533496000901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
19,533500500901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
20,533497200901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
21,533496800901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
22,533498700901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
23,533494600901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
24,533496300901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
25,533490500901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
26,533495900901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
27,533495400901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
28,524780510601,106,ComplejoRivieraMaya,2023-05-10,2024-05-14,370,AllInclusive,13200,COLDeluxeGardenView,2,2,2,0,0,26040305,1,RUMAYACCR,524780010601,1500,PesoMexicano,3,119300,0,0,0,2022-12-1900:00:00.000,2024-02-0517:47:08.000,2023-03-1400:00:00.000,0,NaN,30072.00,0.00,0.0,10286.0,0,30072.00,0.00,0.0,1,0,MEXICO,Weddings,CORPORATE
29,588587210701,107,ComplejoPuntaCana,2023-12-31,2024-01-31,31,AllInclusive,19600,BAVRooftopJTJS,2,2,2,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,Dolar,1,0,58841510700,0,0,2023-09-0400:00:00.000,2023-12-3116:38:24.000,NaN,1528000,PalladiumRewards,8062.87,1984.00,0.0,0.0,0,8062.87,1984.00,0.0,1,0,ALEMANIA,Loyalty,DIRECTSALES

In [34]:
# Veamos si son los mismos casos ordenando por numero de noches
df_Reservas.sort_values("NOCHES", ascending = False).reset_index(drop=True).head(40)

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
0,2754710088011,106,ComplejoRivieraMaya,2023-11-11,2028-11-11,1827,AllInclusive,38600,WSJuniorSuiteGV,2,2,2,0,0,19530901,1,THOMSONGROUP/TUIUKLTD,0,700,Dolar,3,119000,0,0,0,2021-09-0200:00:00.000,2023-11-1205:04:41.000,2021-09-0200:00:00.000,0,NaN,17108.00,0.00,0.0,0.0,1,0.00,0.00,0.0,1,0,REINOUNIDO,FixedRates,T.O./T.A.
1,533501200901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
2,533499200901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
3,533500400901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
4,533500500901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
5,533499300901,9,DominicanFiestaHotel&Casino,2023-02-20,2026-02-26,1102,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45248.28,46630.68,0.0,0.0,0,-45248.28,46630.68,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
6,533495400901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
7,533495900901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
8,533496900901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
9,533496800901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
10,533497600901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
11,533494500901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
12,533490200901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
13,533496000901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
14,533498100901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
15,533496300901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
16,533497000901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
17,533490500901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
18,533490800901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
19,533490600901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
20,533496400901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
21,533495300901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
22,533489800901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
23,533497200901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
24,533498700901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
25,533498200901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
26,533494600901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
27,533493700901,9,DominicanFiestaHotel&Casino,2023-02-21,2026-02-26,1101,MediaPension,51000,DFDELUXECITYVIEW,2,2,2,0,0,23817305,2,DIRECTOVENTAS-MARYE.SOSA,533489300901,700,Dolar,3,119100,0,0,0,2023-02-0200:00:00.000,2023-02-0200:00:00.000,2023-02-0200:00:00.000,0,NaN,-45341.94,46586.10,0.0,0.0,0,-45341.94,46586.10,0.0,1,0,REPUBLICADOMINICANA,GroupLeisure,CORPORATE
28,524780510601,106,ComplejoRivieraMaya,2023-05-10,2024-05-14,370,AllInclusive,13200,COLDeluxeGardenView,2,2,2,0,0,26040305,1,RUMAYACCR,524780010601,1500,PesoMexicano,3,119300,0,0,0,2022-12-1900:00:00.000,2024-02-0517:47:08.000,2023-03-1400:00:00.000,0,NaN,30072.00,0.00,0.0,10286.0,0,30072.00,0.00,0.0,1,0,MEXICO,Weddings,CORPORATE
29,450926709201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-02-01,2023-02-06,370,AllInclusive,37000,JAMJuniorSuiteOFV,2,2,2,0,0,20794505,1,CLASSICVACATIONS,450925809201,700,Dolar,3,119000,0,0,0,2021-12-0900:00:00.000,2021-12-1900:00:00.000,2021-12-1900:00:00.000,0,NaN,18500.00,28120.00,0.0,0.0,1,69547.30,25460.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
30,547161100901,9,DominicanFiestaHotel&Casino,2023-03-31,2023-12-31,275,AlojamientoyDesayuno,51600,DFJUNIORSUITEDLXCV,1,1,1,0,0,20692505,2,EMPORIOLUISMEDRANO,0,700,Dolar,1,0,18069000900,0,0,2023-03-3114:54:15.000,2023-03-3117:36:32.000,NaN,0,NaN,18832.00,2288.00,0.0,0.0,0,18832.00,2288.00,0.0,1,0,REPUBLICADOMINICANA,FixedRates,CORPORATE
31,451209309200,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-04-15,2022-12-18,247,AllInclusive,43300,LHJuniorSuiteBSOV,2,2,2,0,0,19531901,1,VACATIONEXPRESS,435482209201,700,Dolar,3,119100,0,0,0,2021-09-0900:00:00.000,2021-12-1200:00:00.000,2021-12-1200:00:00.000,0,NaN,9386.00,18772.00,0.0,0.0,1,91506.10,18772.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
32,451209209200,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-04-15,2022-12-18,247,AllInclusive,43300,LHJuniorSuiteBSOV,2,2,2,0,0,19531901,1,VACATIONEXPRESS,435482209201,700,Dolar,3,119100,0,0,0,2021-09-0900:00:00.000,2021-12-1200:00:00.000,2021-12-1200:00:00.000,0,NaN,9386.00,18772.00,0.0,0.0,1,91506.10,18772.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
33,510678900901,9,DominicanFiestaHotel&Casino,2022-10-12,2023-03-06,145,AlojamientoyDesayuno,56100,DFMASTERSUITEPV,2,2,2,0,0,23817405,2,DIRECTOVENTAS-DESIJIMENEZ,0,700,Dolar,1,0,17065900900,0,0,2022-09-2900:00:00.000,2022-10-1200:00:00.000,NaN,0,NaN,10895.36,1863.68,0.0,0.0,0,10895.36,1863.68,0.0,1,0,HAITI,FixedRates,CORPORATE
34,387264309201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-07-07,2022-11-07,123,AllInclusive,11200,JAMJuniorSuiteGV,2,2,2,0,0,21795305,1,FUNJETVACATIONSALG,387259109201,700,Dolar,3,119000,0,0,0,2020-11-1000:00:00.000,2022-05-0400:00:00.000,2022-05-0400:00:00.000,0,NaN,6150.00,9348.00,0.0,0.0,1,27628.80,9348.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
35,533147600901,9,DominicanFiestaHotel&Casino,2023-02-01,2023-05-25,113,AlojamientoyDesayuno,51300,DFDELUXEPOOLVIEWBALCO,1,1,1,0,0,23817405,2,DIRECTOVENTAS-DESIJIMENEZ,0,700,Dolar,1,53400,17694000900,0,0,2023-02-0100:00:00.000,2023-02-0100:00:00.000,NaN,0,NaN,7051.20,940.16,0.0,0.0,0,7051.20,940.16,0.0,1,0,REPUBLICADOMINICANA,FixedRates,CORPORATE
36,549298400901,9,DominicanFiestaHotel&Casino,2023-04-13,2023-07-15,93,AlojamientoyDesayuno,51400,DFEXECUTIVECITYVIEW,1,1,1,0,0,270,2,"MARMOTECH,S.A.",0,700,Dolar,1,0,18140700900,0,0,2023-04-1311:35:50.000,2023-04-1321:18:29.000,NaN,0,NaN,7320.96,773.76,0.0,0.0,0,7320.96,773.76,0.0,1,0,REPUBLICADOMINICANA,FixedRates,CORPORATE
37,530798709201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-03-01,2023-05-24,84,AllInclusive,11200,JAMJuniorSuiteGV,2,2,2,0,0,19591201,1,BOOKINGEUROPEBV,0,700,Dolar,3,0,0,0,0,2023-01-2200:00:00.000,2023-03-0211:01:43.000,2023-02-0900:00:00.000,0,NaN,44732.75,6384.00,0.0,0.0,0,44732.75,6384.00,0.0,1,0,ALEMANIA,BAR,E-COMMERCE
38,454785009201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-01-06,2022-03-24,77,AllInclusive,43200,LHJuniorSuiteBS,1,1,1,0,0,20341305,1,CALLCENTER,0,700,Dolar,3,0,0,0,0,2022-01-0500:00:00.000,2022-01-1100:00:00.000,2022-01-1100:00:00.000,0,NaN,26459.91,2926.00,0.0,0.0,0,26459.91,2926.00,0.0,1,0,ESTADOSUNIDOS,Package,DIRECTSALES
39,489154110701,107,ComplejoPuntaCana,2023-02-08,2023-04-23,74,AllInclusive,30800,BAVAmbassadorSuitePOV,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,Dolar,3,0,0,0,0,2022-06-0900:00:00.000,2022-06-3000:00:00.000,2022-06-3000:00:00.000,0,NaN,19555.98,4736.00,0.0,0.0,0,19555.98,4736.00,0.0,1,0,SUIZA,Fixedrates,DIRECTSALES

In [35]:
# Vemos que hasta 370 días incluidos hay datos claramente erróneos que nos contaminarían en aprendizaje
# Aún así, si por algún motivo deseamos cambiar dicho corte, estableceremos una variable

limite_noches = 370

df_Reservas = df_Reservas.loc[df_Reservas['NOCHES'] < limite_noches].reset_index(drop=True)

In [36]:
# Recomprobamos LLEGADA

# La llegada más temprana
print(min(df_Reservas['LLEGADA']))
# Todo ok

# La llegada más tardía
print(max(df_Reservas['LLEGADA']))
# Todo ok

2022-01-01 00:00:00
2023-12-31 00:00:00

In [37]:
# Recomprobamos SALIDA

# La salida más temprana
print(min(df_Reservas['SALIDA']))
# Todo ok

# La salida más tardía
print(max(df_Reservas['SALIDA']))
# Todo ok

2022-01-02 00:00:00
2024-01-31 00:00:00

In [38]:
# Seguimos
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337938 entries, 0 to 1337937
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337938 non-null  object
 1   ID_HOTEL           1337938 non-null  object
 2   HOTEL              1337938 non-null  object
 3   LLEGADA            1337938 non-null  datetime64[ns]
 4   SALIDA             1337938 non-null  datetime64[ns]
 5   NOCHES             1337938 non-null  int64
 6   REGIMEN            1337921 non-null  object
 7   ID_TIPO            1337938 non-null  object
 8   TIPO               1337938 non-null  object
 9   USO                1337938 non-null  int64
 10  PAX                1337938 non-null  int64
 11  ADULTOS            1337938 non-null  int64
 12  NENES              1337938 non-null  int64
 13  BEBES              1337938 non-null  int64
 14  ID_CLIENTE         1337938 non-null  object
 15  TIPO_CLIENTE       1337938 non-null  object
 16  CLIENTE            1337930 non-null  object
 17  ID_MULTIPLE        1337938 non-null  int64
 18  ID_MONEDA          1337938 non-null  object
 19  MONEDA             1337938 non-null  object
 20  STATUS             1337938 non-null  object
 21  ID_MOTIVO          1337938 non-null  object
 22  ID_CARDEX          1337938 non-null  object
 23  SUPLETORIA         1337938 non-null  int64
 24  CUNAS              1337938 non-null  int64
 25  FECHA_TOMA         1337938 non-null  object
 26  FECHA_MOD          1337659 non-null  object
 27  FECHA_CANCELACION  438545 non-null   object
 28  ID_FIDELIDAD       1337938 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337938 non-null  float64
 31  VALPEN             1337938 non-null  float64
 32  VALSERV            1337938 non-null  float64
 33  VALFIJOS           1337938 non-null  float64
 34  COMERCIALIZADORA   1337938 non-null  int64
 35  CMVALHAB           1337938 non-null  float64
 36  CMVALPEN           1337938 non-null  float64
 37  CMCVALSERV         1337938 non-null  float64
 38  AUTORIZO           1337938 non-null  int64
 39  GRATIS             1337938 non-null  int64
 40  PAIS               1337938 non-null  object
 41  SEGMENTO           1337938 non-null  object
 42  FUENTE_NEGOCIO     1337938 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(12), object(22)
memory usage: 438.9+ MB

#### REGIMEN

In [39]:
# REGIMEN
df_Reservas['REGIMEN'].value_counts(dropna=False)

REGIMEN
AllInclusive            1285731
AlojamientoyDesayuno      35705
SoloAlojamiento           13905
PensionCompleta            1655
MediaPension                925
NaN                          17
Name: count, dtype: int64

In [40]:
# Veamos si hay alguna pista de cómo imputarlo correctamente
df_Reservas.loc[df_Reservas['REGIMEN'].isna()]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
76667,552177909601,96,ComplejoCostaMujeres,2023-05-11,2023-05-15,4,NaN,28100,CMUFSAmbassadorSuiBS,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,1,0,50854909600,0,0,2023-04-2400:00:00.000,2023-05-1117:20:12.000,NaN,1528000,PalladiumRewards,2949.03,0.0,0.0,20.64,0,2949.03,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES
195289,565732809201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-07-06,2023-07-11,5,NaN,37000,JAMJuniorSuiteOFV,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,1,0,63359709200,0,0,2023-05-1000:00:00.000,2023-07-0617:54:33.000,NaN,1528000,PalladiumRewards,4553.46,0.0,0.0,0.00,0,4553.46,0.0,0.0,1,0,JAMAICA,Loyalty,DIRECTSALES
196385,402305809901,99,TRSCapCana,2022-02-16,2022-02-17,1,NaN,32200,CAPJuniorSuiteMV,2,2,2,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,Dolar,3,0,0,0,0,2021-03-1600:00:00.000,2021-03-1600:00:00.000,2021-03-1600:00:00.000,0,NaN,478.26,0.0,0.0,0.00,0,478.26,0.0,0.0,1,0,REPUBLICADOMINICANA,Package,DIRECTSALES
412118,551297509601,96,ComplejoCostaMujeres,2023-05-11,2023-05-15,4,NaN,28100,CMUFSAmbassadorSuiBS,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,9,0,0,0,0,2023-04-2400:00:00.000,2023-05-1202:27:52.000,NaN,1528000,PalladiumRewards,2949.03,0.0,0.0,20.76,0,2949.03,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES
412119,552169009601,96,ComplejoCostaMujeres,2023-05-11,2023-05-15,4,NaN,28100,CMUFSAmbassadorSuiBS,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,9,0,0,0,0,2023-04-2400:00:00.000,2023-05-1202:28:35.000,NaN,1528000,PalladiumRewards,2949.03,0.0,0.0,20.64,0,2949.03,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES
514937,506581709601,96,ComplejoCostaMujeres,2022-10-13,2022-10-18,5,NaN,28100,CMUFSAmbassadorSuiBS,2,3,2,1,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,Dolar,3,0,0,0,0,2022-09-0700:00:00.000,2022-09-1200:00:00.000,2022-09-1200:00:00.000,1528000,PalladiumRewards,6706.40,0.0,0.0,21.45,0,6706.40,0.0,0.0,1,0,SUIZA,Loyalty,DIRECTSALES
590170,552747709201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-05-21,2023-05-23,2,NaN,55000,JAMSupSuitePPOFV,2,2,2,0,0,20341305,1,CALLCENTER,0,700,Dolar,1,0,62611809200,0,0,2023-05-0400:00:00.000,2023-05-2116:42:34.000,NaN,1528000,PalladiumRewards,1157.52,0.0,0.0,0.00,0,1157.52,0.0,0.0,1,0,JAMAICA,Loyalty,DIRECTSALES
723591,476509100601,6,PalladiumVallarta,2022-04-13,2022-04-15,2,NaN,28300,PVRAmbassadorSuitePOV,1,1,1,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,1500,PesoMexicano,1,0,0,0,0,2022-04-1200:00:00.000,2022-04-1300:00:00.000,NaN,0,NaN,31238.00,0.0,0.0,0.00,0,31238.00,0.0,0.0,1,0,MEXICO,BAR,DIRECTSALES
822477,551996509601,96,ComplejoCostaMujeres,2023-05-11,2023-05-15,4,NaN,28100,CMUFSAmbassadorSuiBS,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,9,0,0,0,0,2023-04-2400:00:00.000,2023-05-1202:27:33.000,NaN,1528000,PalladiumRewards,2949.03,0.0,0.0,20.64,0,2949.03,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES
906427,564115609201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-07-06,2023-07-11,5,NaN,37000,JAMJuniorSuiteOFV,2,2,2,0,0,20341305,1,CALLCENTER,0,700,Dolar,1,0,63358509200,0,0,2023-05-1000:00:00.000,2023-07-0617:28:54.000,NaN,1528000,PalladiumRewards,3826.45,0.0,0.0,0.00,0,3826.45,0.0,0.0,1,0,JAMAICA,Loyalty,DIRECTSALES
974849,565735509201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-07-06,2023-07-11,5,NaN,37000,JAMJuniorSuiteOFV,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,1,0,63358809200,0,0,2023-05-1000:00:00.000,2023-07-0617:38:55.000,NaN,1528000,PalladiumRewards,4553.46,0.0,0.0,0.00,0,4553.46,0.0,0.0,1,0,JAMAICA,Loyalty,DIRECTSALES
980606,510563900901,9,DominicanFiestaHotel&Casino,2022-10-03,2022-10-04,1,NaN,51400,DFEXECUTIVECITYVIEW,2,2,2,0,0,20407405,1,PRICETRAVEL(USD),0,700,Dolar,1,53400,17024000900,0,0,2022-09-2800:00:00.000,2022-10-0300:00:00.000,NaN,0,NaN,66.56,0.0,0.0,0.00,0,66.56,0.0,0.0,1,0,CHILE,Package,E-COMMERCE
999020,507477709601,96,ComplejoCostaMujeres,2022-10-13,2022-10-18,5,NaN,28100,CMUFSAmbassadorSuiBS,2,3,2,1,0,23808705,1,PremiumTravelConsultingTatjanaGantenbein,0,700,Dolar,1,0,47042709600,0,0,2022-09-1200:00:00.000,2022-10-1300:00:00.000,NaN,0,NaN,5767.51,0.0,0.0,21.75,0,5767.51,0.0,0.0,1,0,SUIZA,BAR,T.O./T.A.
1060357,552168409601,96,ComplejoCostaMujeres,2023-05-11,2023-05-15,4,NaN,28100,CMUFSAmbassadorSuiBS,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,9,0,0,0,0,2023-04-2400:00:00.000,2023-05-1202:27:54.000,NaN,1528000,PalladiumRewards,2949.03,0.0,0.0,20.64,0,2949.03,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES
1180190,551193809601,96,ComplejoCostaMujeres,2023-05-11,2023-05-15,4,NaN,28100,CMUFSAmbassadorSuiBS,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,9,0,0,0,0,2023-04-2400:00:00.000,2023-05-1202:27:53.000,NaN,1528000,PalladiumRewards,2949.03,0.0,0.0,20.76,0,2949.03,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES
1211747,551293309601,96,ComplejoCostaMujeres,2023-05-11,2023-05-15,4,NaN,28100,CMUFSAmbassadorSuiBS,2,3,3,0,0,20341305,1,CALLCENTER,0,700,Dolar,9,0,0,0,0,2023-04-2400:00:00.000,2023-05-1202:27:26.000,NaN,1528000,PalladiumRewards,2949.03,0.0,0.0,20.76,0,2949.03,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES
1315501,510311800901,9,DominicanFiestaHotel&Casino,2022-10-22,2022-10-24,2,NaN,51400,DFEXECUTIVECITYVIEW,2,2,2,0,0,20407405,1,PRICETRAVEL(USD),0,700,Dolar,9,0,0,0,0,2022-09-2700:00:00.000,2022-09-2700:00:00.000,NaN,0,NaN,118.66,0.0,0.0,0.00,0,118.66,0.0,0.0,1,0,SINPAIS,Package,E-COMMERCE

In [41]:
# Como no vemos ningún indicativo, procedemos a imputar 'Desconocido', por si fuese un indicativo de cancelación
# De todas formas, 17 líneas frente a más de un millón, podríamos dropearlo perfectamente
# Posteriormente ya veremos qué da mejores resultados de predicción

df_Reservas.loc[df_Reservas['REGIMEN'].isna(), 'REGIMEN'] = 'Desconocido'

In [42]:
df_Reservas['REGIMEN'].value_counts(dropna=False)

REGIMEN
AllInclusive            1285731
AlojamientoyDesayuno      35705
SoloAlojamiento           13905
PensionCompleta            1655
MediaPension                925
Desconocido                  17
Name: count, dtype: int64

#### TIPO

In [43]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337938 entries, 0 to 1337937
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337938 non-null  object
 1   ID_HOTEL           1337938 non-null  object
 2   HOTEL              1337938 non-null  object
 3   LLEGADA            1337938 non-null  datetime64[ns]
 4   SALIDA             1337938 non-null  datetime64[ns]
 5   NOCHES             1337938 non-null  int64
 6   REGIMEN            1337938 non-null  object
 7   ID_TIPO            1337938 non-null  object
 8   TIPO               1337938 non-null  object
 9   USO                1337938 non-null  int64
 10  PAX                1337938 non-null  int64
 11  ADULTOS            1337938 non-null  int64
 12  NENES              1337938 non-null  int64
 13  BEBES              1337938 non-null  int64
 14  ID_CLIENTE         1337938 non-null  object
 15  TIPO_CLIENTE       1337938 non-null  object
 16  CLIENTE            1337930 non-null  object
 17  ID_MULTIPLE        1337938 non-null  int64
 18  ID_MONEDA          1337938 non-null  object
 19  MONEDA             1337938 non-null  object
 20  STATUS             1337938 non-null  object
 21  ID_MOTIVO          1337938 non-null  object
 22  ID_CARDEX          1337938 non-null  object
 23  SUPLETORIA         1337938 non-null  int64
 24  CUNAS              1337938 non-null  int64
 25  FECHA_TOMA         1337938 non-null  object
 26  FECHA_MOD          1337659 non-null  object
 27  FECHA_CANCELACION  438545 non-null   object
 28  ID_FIDELIDAD       1337938 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337938 non-null  float64
 31  VALPEN             1337938 non-null  float64
 32  VALSERV            1337938 non-null  float64
 33  VALFIJOS           1337938 non-null  float64
 34  COMERCIALIZADORA   1337938 non-null  int64
 35  CMVALHAB           1337938 non-null  float64
 36  CMVALPEN           1337938 non-null  float64
 37  CMCVALSERV         1337938 non-null  float64
 38  AUTORIZO           1337938 non-null  int64
 39  GRATIS             1337938 non-null  int64
 40  PAIS               1337938 non-null  object
 41  SEGMENTO           1337938 non-null  object
 42  FUENTE_NEGOCIO     1337938 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(12), object(22)
memory usage: 438.9+ MB

In [44]:
# Tenemos distinto menor número de IDs que de tipos
# Eso implica que la relación no es 1:1, y debería

print(df_Reservas['ID_TIPO'].nunique(dropna=False))
print(df_Reservas['TIPO'].nunique(dropna=False))

173
195

In [45]:
# Podríamos estar hablando de 1:n, pero ni eso. Se ha comprobado y es n:n
# Transformar un 1:n en 1:1 se puede hacer con buena seguridad, un n:n con tantos conflictos no, habría que asumir demasiadas cosas como para que el resultado fuera confiable
# Con lo cual, es ID_TIPO no aporta nada bueno
# Lo dejaremos para ver a posteriori si mejora resultados, pero prejuzgando, deberíamos dropearlo

print('1 ID = N TIPOs')
display(df_Reservas.groupby('ID_TIPO')['TIPO'].nunique().sort_values(ascending=False))
print('')
print('1 TIPO = N IDs')
display(df_Reservas.groupby('TIPO')['ID_TIPO'].nunique().sort_values(ascending=False))

1 ID = N TIPOs

ID_TIPO
32600    3
27500    2
27600    2
27300    2
7000     2
26800    2
26600    2
27800    2
27700    2
23100    2
32500    2
29600    2
27400    2
45900    2
46500    2
46700    2
46400    2
46800    2
45800    2
46000    2
46900    2
32400    2
47000    2
47800    2
46600    2
7700     1
9900     1
11200    1
9500     1
20000    1
7500     1
7200     1
5200     1
5000     1
5100     1
4300     1
4000     1
2500     1
8100     1
8700     1
8200     1
9600     1
3100     1
3500     1
3400     1
27200    1
27100    1
23300    1
25800    1
26500    1
26400    1
26700    1
26900    1
11300    1
13000    1
13200    1
13100    1
13300    1
19600    1
19900    1
28300    1
32300    1
32200    1
32700    1
32800    1
33300    1
30100    1
28100    1
27900    1
30300    1
30500    1
30800    1
30600    1
30900    1
31000    1
30200    1
28000    1
38500    1
38600    1
38700    1
38800    1
38900    1
39000    1
39100    1
39200    1
39300    1
39400    1
39500    1
39600    1
39700    1
41500    1
41700    1
41800    1
41900    1
42000    1
42100    1
42200    1
42300    1
33400    1
33500    1
33600    1
33700    1
33800    1
33900    1
34000    1
37000    1
38200    1
38300    1
38400    1
43500    1
43400    1
43300    1
43200    1
43100    1
43000    1
42900    1
42800    1
42700    1
42500    1
42400    1
43600    1
44000    1
44100    1
43800    1
43700    1
45100    1
45000    1
44900    1
44800    1
44700    1
44600    1
44500    1
44400    1
44300    1
46100    1
45600    1
45700    1
45200    1
45400    1
44200    1
43900    1
46300    1
46200    1
47200    1
47100    1
47400    1
47500    1
47600    1
47300    1
47700    1
48400    1
50800    1
50900    1
51000    1
51100    1
51200    1
51300    1
51400    1
51500    1
51600    1
51700    1
51800    1
51900    1
52000    1
54900    1
55000    1
56000    1
56100    1
57100    1
57200    1
57300    1
57400    1
58700    1
Name: TIPO, dtype: int64

1 TIPO = N IDs

TIPO
CAPSuiteJTOV              2
TRSJuniorSuitePSOV        2
TRSJuniorSuitePS          2
TRSJuniorSuiteGV          2
BAVJuniorSuiteGV          1
BAVRomanceSuiteBS         1
BAVPremiumJSGV            1
BAVRooftopJTJS            1
BAVJuniorSuiteSWPOV       1
BAVSignatureSuitePOV      1
BAVRomanceSuiteGV         1
BAVSuperiorJSGV           1
BAVSuperiorJSPOV          1
CAPAmbassadorSTPSOV       1
CAPJuniorSuiteMV          1
CAPJuniorSuitePSOV        1
BAVRooftopJTST            1
CAPJuniorSuiteSWMV        1
BAVSuperiorJSBS           1
CAPJuniorSuiteSWPS        1
CAPSuiteJT                1
CAPSuiteJTMV              1
CAPSuitePSMV              1
CAPSuitePoolsideOV        1
CMUAmbassadorSTBS         1
CMUAmbassadorSWBS         1
CMUFSAmbassadorSuiBS      1
CMUFSJuniorSuiBSPOV       1
CMUFSJuniorSuiteBS        1
CMUFSJuniorSuiteBSOV      1
CMUFSJuniorSuitePABS      1
CMUFSJuniorSuiteSWBS      1
CAPJuniorSuiteSW          1
CMUFSLoftSuiteJTOV        1
CMUFSLoftSuiteJTPOV       1
CMUJuniorSuiteBS          1
CMUJuniorSuiteBSOV        1
CMUJuniorSuiteBSPOV       1
CMUJuniorSuiteGV          1
CMUJuniorSuitePA          1
CMUJuniorSuitePS          1
CMUJuniorSuitePSOV        1
CMUJuniorSuiteSWBS        1
CMULoftSuiteJT            1
CMUResidenceSuiBSPOV      1
CMUSignatureSWBSOV        1
COLAmbassadorSuitePS      1
COLDeluxeGardenView       1
COLJuniorSuiteGV          1
COLJuniorSuitePS          1
COLRomanceVillaSuiPS      1
DFAMBASSADORSTOV          1
DFDELUXECITYVIEW          1
DFDELUXECITYVIEWBALCO     1
DFDELUXEPOOLVIEW          1
DFDELUXEPOOLVIEWBALCO     1
DFEXECUTIVECITYVIEW       1
DFEXECUTIVEOCEANVIEW      1
DFJUNIORSUITEDLXCV        1
DFJUNIORSUITEEXTCV        1
DFMASTERSUITEPV           1
DFSUITEDELUXEPV           1
DFSUITEEXECUTIVEOV        1
Deluxe                    1
CMUFSLoftSuiteJT          1
BAVJuniorSuiteBS          1
BAVAmbassadorSuitePOV     1
JAMJuniorSuiteGV          1
DobleExecutive            1
DobleEstandar             1
JAMJuniorSuiteOFV         1
JAMSuiteOFV               1
JAMJuniorSuitePS          1
JAMJuniorSuitePSOV        1
JAMSuiteGardenView        1
JuniorSuite               1
JuniorSuiteDeluxe         1
JuniorSuiteEstandar       1
JuniorSuiteExecutive      1
KANAmbassadorSuite        1
JAMSupJSPPBS              1
JAMSupJSPPOV              1
JAMSupSuitePPOFV          1
KANJuniorSuiteGV          1
KANResidenceSuiteBS       1
KANRomanceVillaSuiBS      1
LHAmbassadorSuiteBSOV     1
LHJuniorSuiteBS           1
LHJuniorSuiteBSOV         1
LHJuniorSuiteGV           1
LHJuniorSuiteOV           1
LHRomanceVillaSTOV        1
LHSignatureResidence      1
LHSuiteBS                 1
LHSuiteBSOV               1
LHSuiteBSPOV              1
KANDeluxeGardenView       1
KANFSJSSWIMUP             1
KANFSJUNIORSUITEGV        1
NoUsar*CMUJSBS            1
NoUsar*CMUJSBSOV          1
NoUsar*CMUJSBSPOV         1
NoUsar*CMUJSSWBS          1
PALDeluxeBSPOV            1
PALDeluxeBeachside        1
PALDeluxeGardenView       1
PALJuniorSuiteBS          1
PALJuniorSuiteBSOV        1
PALJuniorSuiteGV          1
PALJuniorSuiteSWBS        1
PALLoftSuiteBS            1
PALLoftSuiteBSPOV         1
PALLoftSuiteGV            1
PCDeluxeGardenView        1
PCDeluxePoolside          1
PCJuniorSuiteGV           1
PCJuniorSuitePoolside     1
PCLoftFamilySuite         1
PCLoftSuiteGV             1
PCPremiumJSPS             1
PVRAmbassadorSuitePOV     1
PVRDeluxeGardenView       1
PVRDeluxeOFV              1
PVRDeluxeOceanView        1
PVRDeluxePOV              1
PVRFSJuniorSuiteGV        1
PVRJuniorSuiteGV          1
PVRJuniorSuiteOV          1
LHSuiteGV                 1
LHSuiteOV                 1
NoUsar*CMUAMBSTBS         1
PremiumJuniorSuite        1
PVRSuitePOV               1
PVRSignatureSuitePOV      1
Presidencial              1
SSASLJuniorSuite          1
Suite                     1
SSAJuniorSuitePS          1
SSAJuniorSuiteGV          1
TRSAmbassadorSTBSOV       1
TRSAmbassadorSTSWBSOV     1
TRSAmbassadorSuite        1
TRSAmbassadorSuitePOV     1
TRSCAmbassadorSTBSOV      1
TRSCAmbassadorSTSWBSOV    1
SuiteDeluxe               1
SSAPremiumJSGV            1
TRSCJuniorSuiteBSOV       1
TRSCJuniorSuiteGV         1
TRSCJuniorSuiteSW         1
TRSCJuniorSuiteOV         1
TRSCJuniorSuiteSWBSOV     1
TRSCLoftSuiteBSOV         1
TRSCLoftSuiteJT           1
TRSCJuniorSuiteSWBS       1
TRSCLoftSuiteJTOV         1
TRSCSignatureSTBSPOV      1
TRSJSJacuzziTerrPS        1
TRSCSignatureSTSWBSPOV    1
TRSJacuzziTerrSuiBS       1
TRSJuniorSuiteBS          1
TRSCJuniorSuiteBS         1
SuiteExecutive            1
TRSJuniorSuiteGV/PV       1
TRSJuniorSuiteBSOV        1
TRSJuniorSuitePPGV        1
TRSJuniorSuiteOV          1
TRSJuniorSuitePPPS        1
TRSJuniorSuiteSW          1
TRSJuniorSuiteSWBS        1
TRSJuniorSuiteSWBSOV      1
TRSJuniorSuiteSwimUp      1
TRSLoftSuiteBSOV          1
TRSLoftSuiteJT            1
TRSLoftSuiteJTOV          1
TRSRomanceBWbythelake     1
TRSRomanceSuitePS         1
TRSRomanceSuiteSW         1
TRSSTJacuzziTerrPS        1
TRSSignatureSTBSPOV       1
TRSSignatureSTSWBSPOV     1
TRSSuiteGardenView        1
TRSSuitePPGV              1
TRSSuitePPPS              1
TRSSuitePoolside          1
TRSVillaSuitePoolside     1
TRSVillaSuiteSwimUp       1
TripleDeluxe              1
WSJuniorSuiteBS           1
WSJuniorSuiteGV           1
WSRomanceBWbythelake      1
WSSuiteBeachside          1
WSSuiteGardenView         1
z.DobleExecutive          1
z.PremiumJuniorSuite      1
Name: ID_TIPO, dtype: int64

#### PAX

In [46]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337938 entries, 0 to 1337937
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337938 non-null  object
 1   ID_HOTEL           1337938 non-null  object
 2   HOTEL              1337938 non-null  object
 3   LLEGADA            1337938 non-null  datetime64[ns]
 4   SALIDA             1337938 non-null  datetime64[ns]
 5   NOCHES             1337938 non-null  int64
 6   REGIMEN            1337938 non-null  object
 7   ID_TIPO            1337938 non-null  object
 8   TIPO               1337938 non-null  object
 9   USO                1337938 non-null  int64
 10  PAX                1337938 non-null  int64
 11  ADULTOS            1337938 non-null  int64
 12  NENES              1337938 non-null  int64
 13  BEBES              1337938 non-null  int64
 14  ID_CLIENTE         1337938 non-null  object
 15  TIPO_CLIENTE       1337938 non-null  object
 16  CLIENTE            1337930 non-null  object
 17  ID_MULTIPLE        1337938 non-null  int64
 18  ID_MONEDA          1337938 non-null  object
 19  MONEDA             1337938 non-null  object
 20  STATUS             1337938 non-null  object
 21  ID_MOTIVO          1337938 non-null  object
 22  ID_CARDEX          1337938 non-null  object
 23  SUPLETORIA         1337938 non-null  int64
 24  CUNAS              1337938 non-null  int64
 25  FECHA_TOMA         1337938 non-null  object
 26  FECHA_MOD          1337659 non-null  object
 27  FECHA_CANCELACION  438545 non-null   object
 28  ID_FIDELIDAD       1337938 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337938 non-null  float64
 31  VALPEN             1337938 non-null  float64
 32  VALSERV            1337938 non-null  float64
 33  VALFIJOS           1337938 non-null  float64
 34  COMERCIALIZADORA   1337938 non-null  int64
 35  CMVALHAB           1337938 non-null  float64
 36  CMVALPEN           1337938 non-null  float64
 37  CMCVALSERV         1337938 non-null  float64
 38  AUTORIZO           1337938 non-null  int64
 39  GRATIS             1337938 non-null  int64
 40  PAIS               1337938 non-null  object
 41  SEGMENTO           1337938 non-null  object
 42  FUENTE_NEGOCIO     1337938 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(12), object(22)
memory usage: 438.9+ MB

In [47]:
# Todas las columnas de personas son int, bien
# Vamos a ver si cuadran entre ellas

# Esto debería dar 0
df_Reservas['PAX'].sum()-df_Reservas['ADULTOS'].sum()-df_Reservas['NENES'].sum()-df_Reservas['BEBES'].sum()

np.int64(-42084)

In [48]:
# Puede que el sistema no considere que los bebés sean personas
df_Reservas['PAX'].sum()-df_Reservas['ADULTOS'].sum()-df_Reservas['NENES'].sum()

np.int64(2)

In [49]:
# Nos vamos acercando, pero aún así vemos que hay 1 o 2 filas erróneas... Cuáles?
df_Reservas.loc[df_Reservas['PAX'] != df_Reservas['ADULTOS'] + df_Reservas['NENES']]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
951977,509379110701,107,ComplejoPuntaCana,2022-10-15,2022-10-19,4,AllInclusive,39000,PCLoftSuiteGV,2,2,0,0,0,21087805,1,GRUPOSCOLOMBIA,509367010701,700,Dolar,1,53400,47626410700,0,0,2022-09-2100:00:00.000,2022-10-1500:00:00.000,NaN,0,NaN,184.0,128.0,0.0,0.0,0,184.0,128.0,0.0,1,0,COLOMBIA,GroupLeisure,CORPORATE

In [50]:
# Tedríamos que adivinar si se trata de cualquier conbinación entre niños y adultos que de 2...
# Lo dropeamos, una línea no es nada
df_Reservas = df_Reservas.drop(951977)

In [51]:
# Resulta curioso cómo las camas supletorias son muuuuy inferiores a los nenes y al sobreuso de las habitaciones, pero en fin...
# Siguiente

#### CLIENTE

In [52]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337937 entries, 0 to 1337937
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337937 non-null  object
 1   ID_HOTEL           1337937 non-null  object
 2   HOTEL              1337937 non-null  object
 3   LLEGADA            1337937 non-null  datetime64[ns]
 4   SALIDA             1337937 non-null  datetime64[ns]
 5   NOCHES             1337937 non-null  int64
 6   REGIMEN            1337937 non-null  object
 7   ID_TIPO            1337937 non-null  object
 8   TIPO               1337937 non-null  object
 9   USO                1337937 non-null  int64
 10  PAX                1337937 non-null  int64
 11  ADULTOS            1337937 non-null  int64
 12  NENES              1337937 non-null  int64
 13  BEBES              1337937 non-null  int64
 14  ID_CLIENTE         1337937 non-null  object
 15  TIPO_CLIENTE       1337937 non-null  object
 16  CLIENTE            1337929 non-null  object
 17  ID_MULTIPLE        1337937 non-null  int64
 18  ID_MONEDA          1337937 non-null  object
 19  MONEDA             1337937 non-null  object
 20  STATUS             1337937 non-null  object
 21  ID_MOTIVO          1337937 non-null  object
 22  ID_CARDEX          1337937 non-null  object
 23  SUPLETORIA         1337937 non-null  int64
 24  CUNAS              1337937 non-null  int64
 25  FECHA_TOMA         1337937 non-null  object
 26  FECHA_MOD          1337658 non-null  object
 27  FECHA_CANCELACION  438545 non-null   object
 28  ID_FIDELIDAD       1337937 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337937 non-null  float64
 31  VALPEN             1337937 non-null  float64
 32  VALSERV            1337937 non-null  float64
 33  VALFIJOS           1337937 non-null  float64
 34  COMERCIALIZADORA   1337937 non-null  int64
 35  CMVALHAB           1337937 non-null  float64
 36  CMVALPEN           1337937 non-null  float64
 37  CMCVALSERV         1337937 non-null  float64
 38  AUTORIZO           1337937 non-null  int64
 39  GRATIS             1337937 non-null  int64
 40  PAIS               1337937 non-null  object
 41  SEGMENTO           1337937 non-null  object
 42  FUENTE_NEGOCIO     1337937 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(12), object(22)
memory usage: 449.1+ MB

In [53]:
# Tendremos problemas con los IDs?
print(df_Reservas['ID_CLIENTE'].nunique(dropna=False))
print(df_Reservas['CLIENTE'].nunique(dropna=False))

1405
1438

In [54]:
# Hay más clientes que IDs, tendríamos que inventarnos IDs para solucionarlo

In [55]:
# Vamos a ver si por lo menos la relación es 1:n / n:1

print('1 ID = N CLIENTEs')
display(df_Reservas.groupby('ID_CLIENTE')['CLIENTE'].nunique(dropna=False).sort_values(ascending=False))
print('')
print('1 CLIENTE = N IDs')
display(df_Reservas.groupby('CLIENTE')['ID_CLIENTE'].nunique(dropna=False).sort_values(ascending=False))

1 ID = N CLIENTEs

ID_CLIENTE
20004605    3
19620701    2
19632201    2
20440705    2
19636301    2
           ..
26204405    1
55600900    1
82200900    1
94400900    1
157         1
Name: CLIENTE, Length: 1405, dtype: int64

1 CLIENTE = N IDs

CLIENTE
CONDORFLUGDIENSTGMBH                     2
PRICERES                                 2
(Ecomm)CLUBTURAVIASAdeCV                 1
(NOUSAR)BADATOURS                        1
(NOUSAR)GLOBALTRAVELINTERNATIONAL(FL)    1
                                        ..
WORLDEXPERIENCESXLAPARA                  1
WORLDPASS                                1
WORLDTRAVELSPECIALISTSDELAWARE           1
WORLDVIEWTRAVELNEWYORK                   1
AAAOHIOAUTOCLUB                          1
Name: ID_CLIENTE, Length: 1437, dtype: int64

In [56]:
# Ahora mismo la relación es n:n
# Pero vamos a ver si rellenando los nans de CLIENTE podemos convertirla a 1:n / n:1 y con eso ya podríamos trabajar

df_Reservas.loc[df_Reservas['CLIENTE'].isna()]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
11342,520030609201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-05-04,2023-05-11,7,AllInclusive,43000,JAMSuiteOFV,2,3,2,1,1,0,3,NaN,0,700,Dolar,3,0,0,0,1,2022-11-2300:00:00.000,2023-05-0504:27:35.000,2022-11-2400:00:00.000,0,NaN,1174.60,665.0,0.0,0.0,0,1174.60,665.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
318218,519995309201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-02-11,2023-02-18,7,AllInclusive,11300,JAMSuiteGardenView,2,2,2,0,1,0,3,NaN,0,700,Dolar,3,0,0,0,1,2022-11-2300:00:00.000,2022-11-2400:00:00.000,2022-11-2400:00:00.000,0,NaN,2072.00,532.0,0.0,0.0,0,2072.00,532.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
345448,564422009201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-09-04,2023-09-25,21,AllInclusive,37000,JAMJuniorSuiteOFV,1,1,1,0,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2023-06-2600:00:00.000,2023-09-0509:08:38.000,2023-07-1000:00:00.000,0,NaN,2447.76,798.0,0.0,0.0,0,2447.76,798.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
399782,568685309201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-12-19,2023-12-28,9,AllInclusive,43000,JAMSuiteOFV,2,3,3,0,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2023-07-0300:00:00.000,2023-12-2006:52:22.000,2023-07-1000:00:00.000,0,NaN,3250.29,1026.0,0.0,0.0,0,3250.29,1026.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
582615,564224209201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-08-25,2023-09-02,8,AllInclusive,11200,JAMJuniorSuiteGV,1,3,1,2,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2023-06-2500:00:00.000,2023-08-2607:38:01.000,2023-07-1000:00:00.000,0,NaN,770.88,760.0,0.0,0.0,0,770.88,760.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
680752,520028509201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-05-06,2023-05-13,7,AllInclusive,37000,JAMJuniorSuiteOFV,2,3,3,0,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2022-11-2300:00:00.000,2023-05-0704:24:17.000,2022-11-2400:00:00.000,0,NaN,1471.54,798.0,0.0,0.0,0,1471.54,798.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
1126017,564224109201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-08-25,2023-09-02,8,AllInclusive,11200,JAMJuniorSuiteGV,1,2,1,1,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2023-06-2500:00:00.000,2023-08-2607:37:30.000,2023-07-1000:00:00.000,0,NaN,922.88,608.0,0.0,0.0,0,922.88,608.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
1153836,519993609201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-02-10,2023-02-17,7,AllInclusive,11200,JAMJuniorSuiteGV,2,3,2,1,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2022-11-2300:00:00.000,2022-11-2400:00:00.000,2022-11-2400:00:00.000,0,NaN,1771.00,665.0,0.0,0.0,0,1771.00,665.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE

In [57]:
# Mismos que si filtramos por ID = 0?

df_Reservas.loc[df_Reservas['ID_CLIENTE'].astype(str) == '0']

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
11342,520030609201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-05-04,2023-05-11,7,AllInclusive,43000,JAMSuiteOFV,2,3,2,1,1,0,3,NaN,0,700,Dolar,3,0,0,0,1,2022-11-2300:00:00.000,2023-05-0504:27:35.000,2022-11-2400:00:00.000,0,NaN,1174.60,665.0,0.0,0.0,0,1174.60,665.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
318218,519995309201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-02-11,2023-02-18,7,AllInclusive,11300,JAMSuiteGardenView,2,2,2,0,1,0,3,NaN,0,700,Dolar,3,0,0,0,1,2022-11-2300:00:00.000,2022-11-2400:00:00.000,2022-11-2400:00:00.000,0,NaN,2072.00,532.0,0.0,0.0,0,2072.00,532.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
345448,564422009201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-09-04,2023-09-25,21,AllInclusive,37000,JAMJuniorSuiteOFV,1,1,1,0,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2023-06-2600:00:00.000,2023-09-0509:08:38.000,2023-07-1000:00:00.000,0,NaN,2447.76,798.0,0.0,0.0,0,2447.76,798.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
399782,568685309201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-12-19,2023-12-28,9,AllInclusive,43000,JAMSuiteOFV,2,3,3,0,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2023-07-0300:00:00.000,2023-12-2006:52:22.000,2023-07-1000:00:00.000,0,NaN,3250.29,1026.0,0.0,0.0,0,3250.29,1026.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
582615,564224209201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-08-25,2023-09-02,8,AllInclusive,11200,JAMJuniorSuiteGV,1,3,1,2,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2023-06-2500:00:00.000,2023-08-2607:38:01.000,2023-07-1000:00:00.000,0,NaN,770.88,760.0,0.0,0.0,0,770.88,760.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
680752,520028509201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-05-06,2023-05-13,7,AllInclusive,37000,JAMJuniorSuiteOFV,2,3,3,0,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2022-11-2300:00:00.000,2023-05-0704:24:17.000,2022-11-2400:00:00.000,0,NaN,1471.54,798.0,0.0,0.0,0,1471.54,798.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
1126017,564224109201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-08-25,2023-09-02,8,AllInclusive,11200,JAMJuniorSuiteGV,1,2,1,1,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2023-06-2500:00:00.000,2023-08-2607:37:30.000,2023-07-1000:00:00.000,0,NaN,922.88,608.0,0.0,0.0,0,922.88,608.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE
1153836,519993609201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-02-10,2023-02-17,7,AllInclusive,11200,JAMJuniorSuiteGV,2,3,2,1,0,0,3,NaN,0,700,Dolar,3,0,0,0,0,2022-11-2300:00:00.000,2022-11-2400:00:00.000,2022-11-2400:00:00.000,0,NaN,1771.00,665.0,0.0,0.0,0,1771.00,665.0,0.0,1,0,SINPAIS,FixedRates,CORPORATE

In [58]:
# Vemos que todas han sido canceladas, justo después de efectuar su reserva o al poco tiempo
# El hecho de que no tengan cliente es alarmante. Dudosamente una plataforma de reserva permitiría el avance sin rellenar ese dato
# Es de suponer que se trata de algún chanchullo del gerente de turno que al final se quedó en nada... Dropeamos
df_Reservas = df_Reservas.drop([
    11342,
    318218,
    345448,
    399782,
    582615,
    680752,
    1126017,
    1153836
])

In [59]:
# Volvemos a comprobar las relaciones

print('1 ID = N CLIENTEs')
display(df_Reservas.groupby('ID_CLIENTE')['CLIENTE'].nunique(dropna=False).sort_values(ascending=False))
print('')
print('1 CLIENTE = N IDs')
display(df_Reservas.groupby('CLIENTE')['ID_CLIENTE'].nunique(dropna=False).sort_values(ascending=False))

1 ID = N CLIENTEs

ID_CLIENTE
20004605     3
20328805     2
19702200     2
19593501     2
19620701     2
            ..
26204405     1
55600900     1
82200900     1
94400900     1
354500900    1
Name: CLIENTE, Length: 1404, dtype: int64

1 CLIENTE = N IDs

CLIENTE
CONDORFLUGDIENSTGMBH                     2
PRICERES                                 2
(Ecomm)CLUBTURAVIASAdeCV                 1
(NOUSAR)BADATOURS                        1
(NOUSAR)GLOBALTRAVELINTERNATIONAL(FL)    1
                                        ..
WORLDEXPERIENCESXLAPARA                  1
WORLDPASS                                1
WORLDTRAVELSPECIALISTSDELAWARE           1
WORLDVIEWTRAVELNEWYORK                   1
AAAOHIOAUTOCLUB                          1
Name: ID_CLIENTE, Length: 1437, dtype: int64

In [60]:
# Sigue siendo n:n, no merece la pena perder el tiempo
# Dejamos ID para probar resultados de predicción pero yo lo dropearía

In [61]:
# ID_MULTIPLE
# Del diccionario de datos: Indica si es una reserva de grupo o no, ID >0 indica que es de grupo
# Pues renombramos columna a GRUPO
df_Reservas = df_Reservas.rename(columns={'ID_MULTIPLE': 'GRUPO'})
# Y ponemos 1 o 0 como booleano (int para facilidad de cálculo)
df_Reservas.loc[df_Reservas['GRUPO'] > 0, 'GRUPO'] = 1

In [62]:
# Vemos que la mayoría no van en grupo
df_Reservas['GRUPO'].value_counts(dropna=False)

GRUPO
0    1175731
1     162198
Name: count, dtype: int64

#### MONEDA

In [63]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337929 entries, 0 to 1337937
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337929 non-null  object
 1   ID_HOTEL           1337929 non-null  object
 2   HOTEL              1337929 non-null  object
 3   LLEGADA            1337929 non-null  datetime64[ns]
 4   SALIDA             1337929 non-null  datetime64[ns]
 5   NOCHES             1337929 non-null  int64
 6   REGIMEN            1337929 non-null  object
 7   ID_TIPO            1337929 non-null  object
 8   TIPO               1337929 non-null  object
 9   USO                1337929 non-null  int64
 10  PAX                1337929 non-null  int64
 11  ADULTOS            1337929 non-null  int64
 12  NENES              1337929 non-null  int64
 13  BEBES              1337929 non-null  int64
 14  ID_CLIENTE         1337929 non-null  object
 15  TIPO_CLIENTE       1337929 non-null  object
 16  CLIENTE            1337929 non-null  object
 17  GRUPO              1337929 non-null  int64
 18  ID_MONEDA          1337929 non-null  object
 19  MONEDA             1337929 non-null  object
 20  STATUS             1337929 non-null  object
 21  ID_MOTIVO          1337929 non-null  object
 22  ID_CARDEX          1337929 non-null  object
 23  SUPLETORIA         1337929 non-null  int64
 24  CUNAS              1337929 non-null  int64
 25  FECHA_TOMA         1337929 non-null  object
 26  FECHA_MOD          1337650 non-null  object
 27  FECHA_CANCELACION  438537 non-null   object
 28  ID_FIDELIDAD       1337929 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337929 non-null  float64
 31  VALPEN             1337929 non-null  float64
 32  VALSERV            1337929 non-null  float64
 33  VALFIJOS           1337929 non-null  float64
 34  COMERCIALIZADORA   1337929 non-null  int64
 35  CMVALHAB           1337929 non-null  float64
 36  CMVALPEN           1337929 non-null  float64
 37  CMCVALSERV         1337929 non-null  float64
 38  AUTORIZO           1337929 non-null  int64
 39  GRATIS             1337929 non-null  int64
 40  PAIS               1337929 non-null  object
 41  SEGMENTO           1337929 non-null  object
 42  FUENTE_NEGOCIO     1337929 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(12), object(22)
memory usage: 449.1+ MB

In [64]:
# IDs y MONEDA casan?

print(df_Reservas['ID_MONEDA'].nunique(dropna=False))
print(df_Reservas['MONEDA'].nunique(dropna=False))

5
5

In [65]:
# Vamos a ver si por lo menos la relación es 1:n / n:1

print('1 ID = N MONEDAs')
display(df_Reservas.groupby('ID_MONEDA')['MONEDA'].nunique(dropna=False).sort_values(ascending=False))
print('')
print('1 MONEDA = N IDs')
display(df_Reservas.groupby('MONEDA')['ID_MONEDA'].nunique(dropna=False).sort_values(ascending=False))

1 ID = N MONEDAs

ID_MONEDA
700     1
800     1
900     1
1400    1
1500    1
Name: MONEDA, dtype: int64

1 MONEDA = N IDs

MONEDA
Dolar             1
Dolarjamaicano    1
PesoDominicano    1
PesoMexicano      1
Real              1
Name: ID_MONEDA, dtype: int64

In [66]:
# Todo OK
# Lo que sí vamos a hacer es sustituir sus nombres por el acrónimo de divisa internacional oficial
df_Reservas.loc[df_Reservas['MONEDA'] == 'Dolar', 'MONEDA'] = 'USD'
df_Reservas.loc[df_Reservas['MONEDA'] == 'Dolarjamaicano', 'MONEDA'] = 'JMD'
df_Reservas.loc[df_Reservas['MONEDA'] == 'PesoDominicano', 'MONEDA'] = 'DOP'
df_Reservas.loc[df_Reservas['MONEDA'] == 'PesoMexicano', 'MONEDA'] = 'MXN'
df_Reservas.loc[df_Reservas['MONEDA'] == 'Real', 'MONEDA'] = 'BRL'

In [67]:
# Con el 02_Generador_tipo_cambiario hemos generado un dataset en csv
# Lo leemos y convertimos a DF
df_Moneda = pd.read_csv(r'D:\DEV\Python\00_TFM_PALLADIUM\02_DATASETS_GENERADOS\USD_X.csv')

In [68]:
# Comprobamos que está bien leído
df_Moneda.head()

        FECHA  USD         JMD        DOP        MXN     BRL
0  2018-01-01    1  122.900002  47.618999  19.650850  3.3076
1  2018-01-02    1  122.779999  47.743000  19.497400  3.3110
2  2018-01-03    1  122.849998  47.734001  19.351101  3.2578
3  2018-01-04    1  122.540001  47.733002  19.306971  3.2355
4  2018-01-05    1  122.379997  47.886002  19.174000  3.2331

#### STATUS

In [69]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337929 entries, 0 to 1337937
Data columns (total 43 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337929 non-null  object
 1   ID_HOTEL           1337929 non-null  object
 2   HOTEL              1337929 non-null  object
 3   LLEGADA            1337929 non-null  datetime64[ns]
 4   SALIDA             1337929 non-null  datetime64[ns]
 5   NOCHES             1337929 non-null  int64
 6   REGIMEN            1337929 non-null  object
 7   ID_TIPO            1337929 non-null  object
 8   TIPO               1337929 non-null  object
 9   USO                1337929 non-null  int64
 10  PAX                1337929 non-null  int64
 11  ADULTOS            1337929 non-null  int64
 12  NENES              1337929 non-null  int64
 13  BEBES              1337929 non-null  int64
 14  ID_CLIENTE         1337929 non-null  object
 15  TIPO_CLIENTE       1337929 non-null  object
 16  CLIENTE            1337929 non-null  object
 17  GRUPO              1337929 non-null  int64
 18  ID_MONEDA          1337929 non-null  object
 19  MONEDA             1337929 non-null  object
 20  STATUS             1337929 non-null  object
 21  ID_MOTIVO          1337929 non-null  object
 22  ID_CARDEX          1337929 non-null  object
 23  SUPLETORIA         1337929 non-null  int64
 24  CUNAS              1337929 non-null  int64
 25  FECHA_TOMA         1337929 non-null  object
 26  FECHA_MOD          1337650 non-null  object
 27  FECHA_CANCELACION  438537 non-null   object
 28  ID_FIDELIDAD       1337929 non-null  object
 29  FIDELIDAD          211029 non-null   object
 30  VALHAB             1337929 non-null  float64
 31  VALPEN             1337929 non-null  float64
 32  VALSERV            1337929 non-null  float64
 33  VALFIJOS           1337929 non-null  float64
 34  COMERCIALIZADORA   1337929 non-null  int64
 35  CMVALHAB           1337929 non-null  float64
 36  CMVALPEN           1337929 non-null  float64
 37  CMCVALSERV         1337929 non-null  float64
 38  AUTORIZO           1337929 non-null  int64
 39  GRATIS             1337929 non-null  int64
 40  PAIS               1337929 non-null  object
 41  SEGMENTO           1337929 non-null  object
 42  FUENTE_NEGOCIO     1337929 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(12), object(22)
memory usage: 449.1+ MB

In [70]:
# Veamos los valores únicos

df_Reservas['STATUS'].value_counts()

STATUS
1    699873
3    438852
9    190743
2      8392
4        69
Name: count, dtype: int64

In [71]:
# Los 9 están fuera del diccionario de datos
# Tras hablar con palladium y ver que estos en realidad se tratan de una cancelación para posterior reserva realizada por la propia agncia, no se han de tener en cuenta, pues sería más bien una modificación
# Nos recomiendan dropearlas para no introducir ruido
# Y sería un ruido muy considerable habiendo 190.743 registros

df_Reservas = df_Reservas.loc[df_Reservas['STATUS'] != 9]
df_Reservas['STATUS'].value_counts()

STATUS
1    699873
3    438852
2      8392
4        69
Name: count, dtype: int64

In [72]:
# Vamos a revisar que, efectivamente, las canceladas tienen fecha de cancelación y las efectivas no

print('Canceladas según dice su estado')
display(df_Reservas.loc[df_Reservas['STATUS'] > 2, 'FECHA_CANCELACION'].notna().value_counts())
print(' ')
print('Efectivas según dice su estado')
display(df_Reservas.loc[df_Reservas['STATUS'] <= 2, 'FECHA_CANCELACION'].isna().value_counts())

Canceladas según dice su estado

FECHA_CANCELACION
True     438537
False       384
Name: count, dtype: int64

Efectivas según dice su estado

FECHA_CANCELACION
True    708265
Name: count, dtype: int64

In [73]:
# Es decir, que tenemos 384 estancias canceladas sin fecha de cancelación
# Veamos qué pasa con ellas

df_Reservas.loc[(df_Reservas['STATUS'] > 2) & (df_Reservas['FECHA_CANCELACION'].isna())].head()

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
5568,440381410601,106,ComplejoRivieraMaya,2022-06-21,2022-06-28,7,AllInclusive,41800,WSJuniorSuiteBS,2,2,2,0,0,21795305,1,FUNJETVACATIONSALG,1,700,USD,3,119000,0,0,0,2021-10-1200:00:00.000,2021-11-1100:00:00.000,NaN,0,NaN,798.00,0.0,0.0,0.0,1,1601.6,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
7056,444605510701,107,ComplejoPuntaCana,2022-01-15,2022-01-23,8,AllInclusive,33600,TRSJuniorSuiteGV/PV,2,2,2,0,0,19520101,1,"TRAVELPLANBUSINESS,SAU",0,700,USD,3,119000,0,0,0,2021-11-1100:00:00.000,2021-11-1100:00:00.000,NaN,0,NaN,362.88,512.0,0.0,0.0,1,1792.0,512.0,0.0,1,0,ESPANA,FixedRates,T.O./T.A.
14307,386818709201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-04-26,2022-05-03,7,AllInclusive,11200,JAMJuniorSuiteGV,2,2,2,0,0,19605101,1,GOGOLIBERTYTRAVELGROUPDIVISION,1,700,USD,3,119300,0,0,0,2020-11-0400:00:00.000,2020-11-1700:00:00.000,NaN,0,NaN,882.00,0.0,0.0,0.0,1,-532.0,532.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.
14565,481744508300,83,GrandPalladiumImbassaiResort&Spa,2022-12-04,2022-12-11,7,AllInclusive,47600,SSAJuniorSuiteGV,2,2,2,0,0,19574201,1,TOWERTRAVEL,1,700,USD,3,119000,0,0,0,2022-05-0600:00:00.000,2022-05-1000:00:00.000,NaN,0,NaN,5546.80,2114.0,0.0,0.0,1,1330.0,420.0,0.0,1,0,ARGENTINA,FixedRates,T.O./T.A.
14573,481742008300,83,GrandPalladiumImbassaiResort&Spa,2022-12-04,2022-12-11,7,AllInclusive,47600,SSAJuniorSuiteGV,2,2,2,0,0,19574201,1,TOWERTRAVEL,1,700,USD,3,119000,0,0,0,2022-05-0600:00:00.000,2022-05-1000:00:00.000,NaN,0,NaN,5546.80,2114.0,0.0,0.0,1,1330.0,420.0,0.0,1,0,ARGENTINA,FixedRates,T.O./T.A.

In [74]:
# Totalmente inconsistente y sin pistas
# Si realmente han sido canceladas, no me puedo inventar la fecha
# Pero tampoco puedo saber si se han efectuado o no
# No tenemos más remedio que dropear

df_Reservas = df_Reservas.drop(df_Reservas[(df_Reservas['STATUS'] > 2) & (df_Reservas['FECHA_CANCELACION'].isna())].index)

In [75]:
display(df_Reservas.loc[df_Reservas['STATUS'] > 2, 'FECHA_CANCELACION'].notna().value_counts())

FECHA_CANCELACION
True    438537
Name: count, dtype: int64

In [76]:
# Ahora a la inversa, vamos a comprobar que las que tengan fecha de cancelación, tengan status >2

df_Reservas.loc[df_Reservas['FECHA_CANCELACION'].notna(), 'STATUS'].value_counts(dropna=False)

STATUS
3    438468
4        69
Name: count, dtype: int64

In [77]:
# Ahora vamos a crear una nueva columna ['CANCELADA'] 1 o 0 siguiendo la info del diccionario de datos
# 1 y 2 = Efectiva
# resto, cancelada

df_Reservas['CANCELADA'] = 0
df_Reservas.loc[df_Reservas['STATUS'] > 2 , 'CANCELADA'] = 1
df_Reservas.head()

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,CANCELADA
1,456094009201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-12-28,2023-01-04,7,AllInclusive,23300,LHAmbassadorSuiteBSOV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,1,0,60444109200,0,0,2022-01-1300:00:00.000,2022-12-2800:00:00.000,NaN,0,NaN,1868.00,708.00,0.0,0.00,0,1868.00,708.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,0
2,425835909201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-01-22,2022-01-29,7,AllInclusive,43800,LHJuniorSuiteGV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,0,0,0,0,2021-07-1300:00:00.000,2022-01-2000:00:00.000,2022-01-2000:00:00.000,0,NaN,1329.30,665.00,0.0,0.00,0,1329.30,665.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,1
3,549929510601,106,ComplejoRivieraMaya,2023-11-06,2023-11-14,8,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,0,0,0,0,2023-04-1700:00:00.000,2023-11-0704:27:02.000,2023-10-1700:00:00.000,0,NaN,1146.56,1146.56,0.0,12.48,0,1146.56,1146.56,0.0,1,0,CANADA,Fixedrates,DIRECTSALES,1
4,519229110601,106,ComplejoRivieraMaya,2023-11-06,2023-11-23,17,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,0,0,0,0,2023-02-2212:48:29.000,2023-11-0704:27:15.000,2023-09-1400:00:00.000,0,NaN,2436.44,2436.44,0.0,26.52,0,2436.44,2436.44,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,1
5,537405910601,106,ComplejoRivieraMaya,2023-11-25,2023-12-09,14,AllInclusive,13000,COLJuniorSuiteGV,1,1,1,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,0,0,0,0,2023-02-1722:54:38.000,2023-11-2603:57:24.000,2023-04-1100:00:00.000,0,NaN,2413.18,0.00,0.0,21.84,0,2413.18,0.00,0.0,1,0,RUMANIA,Fixedrates,DIRECTSALES,1

In [78]:
# MOTIVO
# Vamos a comprobar la coherencia con el diccionario de datos
df_Reservas['ID_MOTIVO'].value_counts()

ID_MOTIVO
0         843139
53400     229280
119000     52505
119300     13899
119100      4803
53500       2515
181000       346
565300       213
119900        61
678800        30
119800         6
561300         3
53700          2
Name: count, dtype: int64

In [79]:
lista_id_motivo_diccionario = [119300, 561300, 678800, 119000, 119100, 53500, 565300, 119200, 0]

In [80]:
print('Está en el diccionario?')

for id in df_Reservas['ID_MOTIVO'].unique().tolist():
    if id in lista_id_motivo_diccionario:
        print(f'{id} Sí')
    else:
        print(f'{id} NO')

Está en el diccionario?
0 Sí
119000 Sí
53400 NO
119100 Sí
119300 Sí
53500 Sí
181000 NO
565300 Sí
119900 NO
678800 Sí
561300 Sí
119800 NO
53700 NO

In [81]:
print('Está en el dataset?')
for id in lista_id_motivo_diccionario:
    if id in df_Reservas['ID_MOTIVO'].unique().tolist():
        print(f'{id} Sí')
    else:
        print(f'{id} NO')

Está en el dataset?
119300 Sí
561300 Sí
678800 Sí
119000 Sí
119100 Sí
53500 Sí
565300 Sí
119200 NO
0 Sí

In [82]:
# Inconsistente, pero de cara al entrenamiento tampoco nos importa demasiado, pues no podemos saber la causa de la cancelación antes de que ésta se produzca
# Sí que nos importará a posteriori para BI
# Pero de cara a entrenar el modelo no la usaremos por lo comentado, no podemos ver el futuro.
# Renombro los que no están en el diccionario como desconocido_n y listo

In [83]:
# Vamos a cambiar id motivo por motivo, desde la info del diccionario de datos, pero simplificaremos un poco el nombre

# 119300	CANCELACION CLIENTE
# 561300	CANCELACION CON CARGO
# 678800	CANCELACION POR OBRAS
# 119000	CANCELACION TTOO
# 119100	DUPLICIDAD RESERVA
# 53500	    OVERBOOKING
# 565300	RESERVA DESVIADA
# 119200	DESVIO
# 0	        MOT. ANULACION DESCONOCIDO"
# Resto     DESCONOCIDO_N

df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 119300, 'ID_MOTIVO'] = 'CLIENTE'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 561300, 'ID_MOTIVO'] = 'CARGO'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 678800, 'ID_MOTIVO'] = 'OBRAS'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 119000, 'ID_MOTIVO'] = 'TTOO'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 119100, 'ID_MOTIVO'] = 'DUPLICIDAD'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 53500, 'ID_MOTIVO'] = 'OVERBOOKING'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 565300, 'ID_MOTIVO'] = 'R_DESVIADA'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 119200, 'ID_MOTIVO'] = 'DESVIO'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 0, 'ID_MOTIVO'] = 'DESCONOCIDO_0'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 53400, 'ID_MOTIVO'] = 'DESCONOCIDO_1'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 181000, 'ID_MOTIVO'] = 'DESCONOCIDO_2'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 119900, 'ID_MOTIVO'] = 'DESCONOCIDO_3'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 119800, 'ID_MOTIVO'] = 'DESCONOCIDO_4'
df_Reservas.loc[df_Reservas['ID_MOTIVO'] == 53700, 'ID_MOTIVO'] = 'DESCONOCIDO_5'

# Queda pendiente renombrar los desconocidos_n según las preferncias de Palladium

In [84]:
df_Reservas['ID_MOTIVO'].unique()

array(['DESCONOCIDO_0', 'TTOO', 'DESCONOCIDO_1', 'DUPLICIDAD', 'CLIENTE',
       'OVERBOOKING', 'DESCONOCIDO_2', 'R_DESVIADA', 'DESCONOCIDO_3',
       'OBRAS', 'CARGO', 'DESCONOCIDO_4', 'DESCONOCIDO_5'], dtype=object)

In [85]:
#Renombramos columna
df_Reservas = df_Reservas.rename(columns={'ID_MOTIVO': 'MOTIVO'})

In [86]:
df_Reservas.head()

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,CANCELADA
1,456094009201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-12-28,2023-01-04,7,AllInclusive,23300,LHAmbassadorSuiteBSOV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,1,DESCONOCIDO_0,60444109200,0,0,2022-01-1300:00:00.000,2022-12-2800:00:00.000,NaN,0,NaN,1868.00,708.00,0.0,0.00,0,1868.00,708.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,0
2,425835909201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-01-22,2022-01-29,7,AllInclusive,43800,LHJuniorSuiteGV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2021-07-1300:00:00.000,2022-01-2000:00:00.000,2022-01-2000:00:00.000,0,NaN,1329.30,665.00,0.0,0.00,0,1329.30,665.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,1
3,549929510601,106,ComplejoRivieraMaya,2023-11-06,2023-11-14,8,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-04-1700:00:00.000,2023-11-0704:27:02.000,2023-10-1700:00:00.000,0,NaN,1146.56,1146.56,0.0,12.48,0,1146.56,1146.56,0.0,1,0,CANADA,Fixedrates,DIRECTSALES,1
4,519229110601,106,ComplejoRivieraMaya,2023-11-06,2023-11-23,17,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-02-2212:48:29.000,2023-11-0704:27:15.000,2023-09-1400:00:00.000,0,NaN,2436.44,2436.44,0.0,26.52,0,2436.44,2436.44,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,1
5,537405910601,106,ComplejoRivieraMaya,2023-11-25,2023-12-09,14,AllInclusive,13000,COLJuniorSuiteGV,1,1,1,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-02-1722:54:38.000,2023-11-2603:57:24.000,2023-04-1100:00:00.000,0,NaN,2413.18,0.00,0.0,21.84,0,2413.18,0.00,0.0,1,0,RUMANIA,Fixedrates,DIRECTSALES,1

#### CARDEX

In [87]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1146802 entries, 1 to 1337937
Data columns (total 44 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1146802 non-null  object
 1   ID_HOTEL           1146802 non-null  object
 2   HOTEL              1146802 non-null  object
 3   LLEGADA            1146802 non-null  datetime64[ns]
 4   SALIDA             1146802 non-null  datetime64[ns]
 5   NOCHES             1146802 non-null  int64
 6   REGIMEN            1146802 non-null  object
 7   ID_TIPO            1146802 non-null  object
 8   TIPO               1146802 non-null  object
 9   USO                1146802 non-null  int64
 10  PAX                1146802 non-null  int64
 11  ADULTOS            1146802 non-null  int64
 12  NENES              1146802 non-null  int64
 13  BEBES              1146802 non-null  int64
 14  ID_CLIENTE         1146802 non-null  object
 15  TIPO_CLIENTE       1146802 non-null  object
 16  CLIENTE            1146802 non-null  object
 17  GRUPO              1146802 non-null  int64
 18  ID_MONEDA          1146802 non-null  object
 19  MONEDA             1146802 non-null  object
 20  STATUS             1146802 non-null  object
 21  MOTIVO             1146802 non-null  object
 22  ID_CARDEX          1146802 non-null  object
 23  SUPLETORIA         1146802 non-null  int64
 24  CUNAS              1146802 non-null  int64
 25  FECHA_TOMA         1146802 non-null  object
 26  FECHA_MOD          1146523 non-null  object
 27  FECHA_CANCELACION  438537 non-null   object
 28  ID_FIDELIDAD       1146802 non-null  object
 29  FIDELIDAD          154812 non-null   object
 30  VALHAB             1146802 non-null  float64
 31  VALPEN             1146802 non-null  float64
 32  VALSERV            1146802 non-null  float64
 33  VALFIJOS           1146802 non-null  float64
 34  COMERCIALIZADORA   1146802 non-null  int64
 35  CMVALHAB           1146802 non-null  float64
 36  CMVALPEN           1146802 non-null  float64
 37  CMCVALSERV         1146802 non-null  float64
 38  AUTORIZO           1146802 non-null  int64
 39  GRATIS             1146802 non-null  int64
 40  PAIS               1146802 non-null  object
 41  SEGMENTO           1146802 non-null  object
 42  FUENTE_NEGOCIO     1146802 non-null  object
 43  CANCELADA          1146802 non-null  int64
dtypes: datetime64[ns](2), float64(7), int64(13), object(22)
memory usage: 393.7+ MB

In [88]:
# Indica si se ha hecho en checkin, 0 = no, resto = si
# Por tanto, renombramos columna
df_Reservas = df_Reservas.rename(columns={'ID_CARDEX': 'CHECKIN'})
df_Reservas['CHECKIN'].astype(np.int64)
df_Reservas.loc[df_Reservas['CHECKIN'] != 0, 'CHECKIN'] = 1
df_Reservas['CHECKIN'].value_counts()

CHECKIN
1    682797
0    464005
Name: count, dtype: int64

#### FECHAS

In [89]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1146802 entries, 1 to 1337937
Data columns (total 44 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1146802 non-null  object
 1   ID_HOTEL           1146802 non-null  object
 2   HOTEL              1146802 non-null  object
 3   LLEGADA            1146802 non-null  datetime64[ns]
 4   SALIDA             1146802 non-null  datetime64[ns]
 5   NOCHES             1146802 non-null  int64
 6   REGIMEN            1146802 non-null  object
 7   ID_TIPO            1146802 non-null  object
 8   TIPO               1146802 non-null  object
 9   USO                1146802 non-null  int64
 10  PAX                1146802 non-null  int64
 11  ADULTOS            1146802 non-null  int64
 12  NENES              1146802 non-null  int64
 13  BEBES              1146802 non-null  int64
 14  ID_CLIENTE         1146802 non-null  object
 15  TIPO_CLIENTE       1146802 non-null  object
 16  CLIENTE            1146802 non-null  object
 17  GRUPO              1146802 non-null  int64
 18  ID_MONEDA          1146802 non-null  object
 19  MONEDA             1146802 non-null  object
 20  STATUS             1146802 non-null  object
 21  MOTIVO             1146802 non-null  object
 22  CHECKIN            1146802 non-null  object
 23  SUPLETORIA         1146802 non-null  int64
 24  CUNAS              1146802 non-null  int64
 25  FECHA_TOMA         1146802 non-null  object
 26  FECHA_MOD          1146523 non-null  object
 27  FECHA_CANCELACION  438537 non-null   object
 28  ID_FIDELIDAD       1146802 non-null  object
 29  FIDELIDAD          154812 non-null   object
 30  VALHAB             1146802 non-null  float64
 31  VALPEN             1146802 non-null  float64
 32  VALSERV            1146802 non-null  float64
 33  VALFIJOS           1146802 non-null  float64
 34  COMERCIALIZADORA   1146802 non-null  int64
 35  CMVALHAB           1146802 non-null  float64
 36  CMVALPEN           1146802 non-null  float64
 37  CMCVALSERV         1146802 non-null  float64
 38  AUTORIZO           1146802 non-null  int64
 39  GRATIS             1146802 non-null  int64
 40  PAIS               1146802 non-null  object
 41  SEGMENTO           1146802 non-null  object
 42  FUENTE_NEGOCIO     1146802 non-null  object
 43  CANCELADA          1146802 non-null  int64
dtypes: datetime64[ns](2), float64(7), int64(13), object(22)
memory usage: 393.7+ MB

In [90]:
# Tras hablar con Palladium, se ha decidido eliminar horas, dejando sólo fechas
df_Reservas['FECHA_TOMA'] = df_Reservas['FECHA_TOMA'].str[:10]
df_Reservas['FECHA_MOD'] = df_Reservas['FECHA_MOD'].str[:10]
df_Reservas['FECHA_CANCELACION'] = df_Reservas['FECHA_CANCELACION'].str[:10]

In [91]:
# Convertimos a formato fecha
df_Reservas['FECHA_TOMA'] = pd.to_datetime(df_Reservas['FECHA_TOMA'], format='%Y-%m-%d')
df_Reservas['FECHA_MOD'] = pd.to_datetime(df_Reservas['FECHA_MOD'], format='%Y-%m-%d')
df_Reservas['FECHA_CANCELACION'] = pd.to_datetime(df_Reservas['FECHA_CANCELACION'], format='%Y-%m-%d')

In [92]:
df_Reservas.head()

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,MOTIVO,CHECKIN,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,CANCELADA
1,456094009201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-12-28,2023-01-04,7,AllInclusive,23300,LHAmbassadorSuiteBSOV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,1,DESCONOCIDO_0,1,0,0,2022-01-13,2022-12-28,NaT,0,NaN,1868.00,708.00,0.0,0.00,0,1868.00,708.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,0
2,425835909201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-01-22,2022-01-29,7,AllInclusive,43800,LHJuniorSuiteGV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2021-07-13,2022-01-20,2022-01-20,0,NaN,1329.30,665.00,0.0,0.00,0,1329.30,665.00,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,1
3,549929510601,106,ComplejoRivieraMaya,2023-11-06,2023-11-14,8,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-04-17,2023-11-07,2023-10-17,0,NaN,1146.56,1146.56,0.0,12.48,0,1146.56,1146.56,0.0,1,0,CANADA,Fixedrates,DIRECTSALES,1
4,519229110601,106,ComplejoRivieraMaya,2023-11-06,2023-11-23,17,AllInclusive,42000,TRSJuniorSuitePS,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-02-22,2023-11-07,2023-09-14,0,NaN,2436.44,2436.44,0.0,26.52,0,2436.44,2436.44,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,1
5,537405910601,106,ComplejoRivieraMaya,2023-11-25,2023-12-09,14,AllInclusive,13000,COLJuniorSuiteGV,1,1,1,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-02-17,2023-11-26,2023-04-11,0,NaN,2413.18,0.00,0.0,21.84,0,2413.18,0.00,0.0,1,0,RUMANIA,Fixedrates,DIRECTSALES,1

In [93]:
# Comprobaciones

# Toda fecha de toma debe ser anterior a la de modificación y a la de cancelación
# Alguna fila lo incumple?

df_Reservas.loc[df_Reservas['FECHA_TOMA'] > df_Reservas['FECHA_MOD']]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,MOTIVO,CHECKIN,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,CANCELADA
291,414873609201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-07-01,2022-07-06,5,AllInclusive,43200,LHJuniorSuiteBS,1,1,1,0,0,19591201,1,BOOKINGEUROPEBV,0,700,USD,3,DESCONOCIDO_0,0,0,0,2021-05-26,2021-05-25,2021-05-25,0,NaN,1170.10,190.00,0.0,0.0,0,1170.10,190.00,0.0,1,0,ESTADOSUNIDOS,BAR,E-COMMERCE,1
327,579865300901,9,DominicanFiestaHotel&Casino,2023-08-25,2023-08-26,1,AlojamientoyDesayuno,51300,DFDELUXEPOOLVIEWBALCO,1,2,2,0,0,19528401,1,EXPEDIA,0,700,USD,1,DESCONOCIDO_0,1,0,0,2023-08-26,2023-08-25,NaT,1528000,PalladiumRewards,60.13,25.77,0.0,0.0,0,60.13,25.77,0.0,1,0,ESTADOSUNIDOS,BAR,E-COMMERCE,0
824,431777809601,96,ComplejoCostaMujeres,2022-07-11,2022-07-21,10,AllInclusive,46100,CMUFSJuniorSuiBSPOV,2,4,2,2,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,USD,3,DESCONOCIDO_0,0,0,0,2021-08-19,2021-08-18,2021-08-18,0,NaN,5707.10,0.00,0.0,13.0,0,5707.10,0.00,0.0,1,0,CHILE,Package,DIRECTSALES,1
1443,480020209901,99,TRSCapCana,2022-09-05,2022-09-11,6,AllInclusive,48400,CAPJuniorSuiteSWPS,2,2,2,0,0,20455805,1,AGODACOMPANYPTELTD,0,700,USD,3,DESCONOCIDO_0,0,0,0,2022-05-02,2022-05-01,2022-05-01,0,NaN,-215.84,516.00,0.0,0.0,0,-215.84,516.00,0.0,1,0,SINPAIS,BAR,E-COMMERCE,1
1504,526069009201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-01-08,2023-01-12,4,AllInclusive,43800,LHJuniorSuiteGV,2,2,2,0,0,21795205,1,COMMGROUP/CHEAPCARIBBEANALG,0,700,USD,3,DESCONOCIDO_0,0,0,0,2022-12-30,2022-12-29,2022-12-29,0,NaN,152.00,304.00,0.0,0.0,1,1094.80,304.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335085,467912100901,9,DominicanFiestaHotel&Casino,2022-03-08,2022-03-10,2,AlojamientoyDesayuno,51500,DFEXECUTIVEOCEANVIEW,1,1,1,0,0,19528401,1,EXPEDIA,0,700,USD,1,DESCONOCIDO_0,1,0,0,2022-03-09,2022-03-08,NaT,0,NaN,137.28,58.84,0.0,0.0,0,137.28,58.84,0.0,1,0,BELGICA,Package,E-COMMERCE,0
1336290,569626100901,9,DominicanFiestaHotel&Casino,2023-07-07,2023-07-08,1,SoloAlojamiento,51000,DFDELUXECITYVIEW,1,3,3,0,0,19591201,1,BOOKINGEUROPEBV,0,700,USD,1,DESCONOCIDO_0,1,0,0,2023-07-08,2023-07-07,NaT,0,NaN,132.24,0.00,0.0,0.0,0,132.24,0.00,0.0,1,0,REPUBLICADOMINICANA,BAR,E-COMMERCE,0
1336983,518279310601,106,ComplejoRivieraMaya,2023-01-03,2023-01-07,4,AllInclusive,38200,KANDeluxeGardenView,2,3,2,1,0,19674101,1,IMACOPTOURCORPORATION,0,1500,MXN,3,DESCONOCIDO_0,0,0,0,2022-11-15,2022-11-14,2022-11-14,0,NaN,21012.00,0.00,0.0,109.4,0,21012.00,0.00,0.0,1,0,MEXICO,FixedRates,T.O./T.A.,1
1337452,496354809201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-10-10,2022-10-13,3,AllInclusive,4000,LHRomanceVillaSTOV,2,2,2,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,USD,3,DESCONOCIDO_0,0,0,0,2022-07-14,2022-07-13,2022-07-13,0,NaN,1039.59,228.00,0.0,0.0,0,1039.59,228.00,0.0,1,0,CANADA,Package,DIRECTSALES,1
1337670,492545309201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-11-11,2022-11-16,5,AllInclusive,11200,JAMJuniorSuiteGV,1,1,1,0,0,21241205,1,HOTELBEDSUSAINC.,0,700,USD,3,DESCONOCIDO_0,0,0,0,2022-06-26,2022-06-25,2022-06-25,0,NaN,280.00,190.00,0.0,0.0,1,678.40,190.00,0.0,1,0,SINPAIS,BAR,E-COMMERCE,1

In [94]:
# Alguna fila tiene más de un día de diferencia?
df_Reservas.loc[df_Reservas['FECHA_TOMA'] - df_Reservas['FECHA_MOD'] > pd.Timedelta(days=1)]

Empty DataFrame
Columns: [ID_RESERVA, ID_HOTEL, HOTEL, LLEGADA, SALIDA, NOCHES, REGIMEN, ID_TIPO, TIPO, USO, PAX, ADULTOS, NENES, BEBES, ID_CLIENTE, TIPO_CLIENTE, CLIENTE, GRUPO, ID_MONEDA, MONEDA, STATUS, MOTIVO, CHECKIN, SUPLETORIA, CUNAS, FECHA_TOMA, FECHA_MOD, FECHA_CANCELACION, ID_FIDELIDAD, FIDELIDAD, VALHAB, VALPEN, VALSERV, VALFIJOS, COMERCIALIZADORA, CMVALHAB, CMVALPEN, CMCVALSERV, AUTORIZO, GRATIS, PAIS, SEGMENTO, FUENTE_NEGOCIO, CANCELADA]
Index: []

In [95]:
# Puede que la reserva se haya hecho en EEUU y la modificación en Australia... Pero es raro, a comentar con palladium
# Palladium dice que mantenemos

In [96]:
# Misma comprobación con las cancelaciones
df_Reservas.loc[df_Reservas['FECHA_TOMA'] > df_Reservas['FECHA_CANCELACION']]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,MOTIVO,CHECKIN,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,CANCELADA
261,542359210601,106,ComplejoRivieraMaya,2023-03-20,2023-03-24,4,AllInclusive,38200,KANDeluxeGardenView,2,2,2,0,0,19535101,1,SUNWINGTRAVELGROUPINC.,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-03-11,2023-03-21,2023-03-10,0,NaN,820.80,0.00,0.0,6.24,0,820.80,0.00,0.0,1,0,CANADA,FixedRates,T.O./T.A.,1
291,414873609201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-07-01,2022-07-06,5,AllInclusive,43200,LHJuniorSuiteBS,1,1,1,0,0,19591201,1,BOOKINGEUROPEBV,0,700,USD,3,DESCONOCIDO_0,0,0,0,2021-05-26,2021-05-25,2021-05-25,0,NaN,1170.10,190.00,0.0,0.00,0,1170.10,190.00,0.0,1,0,ESTADOSUNIDOS,BAR,E-COMMERCE,1
349,546607509901,99,TRSCapCana,2023-05-26,2023-05-28,2,AllInclusive,32300,CAPJuniorSuitePSOV,2,3,3,0,0,19591201,1,BOOKINGEUROPEBV,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-03-29,2023-05-27,2023-03-28,0,NaN,710.90,314.16,0.0,0.00,0,710.90,314.16,0.0,1,0,REPUBLICADOMINICANA,BAR,E-COMMERCE,1
824,431777809601,96,ComplejoCostaMujeres,2022-07-11,2022-07-21,10,AllInclusive,46100,CMUFSJuniorSuiBSPOV,2,4,2,2,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,USD,3,DESCONOCIDO_0,0,0,0,2021-08-19,2021-08-18,2021-08-18,0,NaN,5707.10,0.00,0.0,13.00,0,5707.10,0.00,0.0,1,0,CHILE,Package,DIRECTSALES,1
1073,593951800601,6,PalladiumVallarta,2023-12-23,2023-12-26,3,AllInclusive,30300,PVRFSJuniorSuiteGV,2,2,2,0,0,19591201,1,BOOKINGEUROPEBV,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-11-07,2023-12-24,2023-11-06,0,NaN,2879.25,0.00,0.0,0.00,0,2879.25,0.00,0.0,1,0,MEXICO,BAR,E-COMMERCE,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1337511,573879909601,96,ComplejoCostaMujeres,2023-08-06,2023-08-11,5,AllInclusive,27500,TRSCLoftSuiteJT,2,2,2,0,0,21793605,1,APPLEVACATIONSALG,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-07-28,2023-08-07,2023-07-27,0,NaN,870.00,0.00,0.0,0.00,1,1872.00,0.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.,1
1337529,559185809601,96,ComplejoCostaMujeres,2023-07-30,2023-08-03,4,AllInclusive,26700,CMULoftSuiteJT,2,2,2,0,0,20736705,1,COSTCOTRAVEL,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-06-04,2023-07-31,2023-06-03,0,NaN,536.00,0.00,0.0,0.00,1,1619.26,0.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.,1
1337537,568168710701,107,ComplejoPuntaCana,2023-07-30,2023-08-05,6,AllInclusive,38800,PCDeluxeGardenView,2,2,2,0,0,19535201,1,JETBLUE,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-06-30,2023-07-31,2023-06-29,0,NaN,272.16,384.00,0.0,0.00,1,750.18,384.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.,1
1337576,562007109601,96,ComplejoCostaMujeres,2023-07-30,2023-08-03,4,AllInclusive,46600,TRSCJuniorSuiteBSOV,2,2,2,0,0,21795105,1,TRAVELIMPRESSIONSALG,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-06-14,2023-07-31,2023-06-13,0,NaN,536.00,0.00,0.0,0.00,1,1401.24,0.00,0.0,1,0,ESTADOSUNIDOS,FixedRates,T.O./T.A.,1
1337670,492545309201,92,GrandPalladiumJamaica&LadyHamiltonResort,2022-11-11,2022-11-16,5,AllInclusive,11200,JAMJuniorSuiteGV,1,1,1,0,0,21241205,1,HOTELBEDSUSAINC.,0,700,USD,3,DESCONOCIDO_0,0,0,0,2022-06-26,2022-06-25,2022-06-25,0,NaN,280.00,190.00,0.0,0.00,1,678.40,190.00,0.0,1,0,SINPAIS,BAR,E-COMMERCE,1

In [97]:
# Alguna fila tiene más de un día de diferencia?
df_Reservas.loc[df_Reservas['FECHA_TOMA'] - df_Reservas['FECHA_CANCELACION'] > pd.Timedelta(days=1)]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,MOTIVO,CHECKIN,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,CANCELADA
9478,495740609601,96,ComplejoCostaMujeres,2023-08-17,2023-08-20,3,AllInclusive,26500,CMUJuniorSuiteGV,2,2,2,0,0,19674601,1,LAOPERADORA.COM,1,1500,MXN,3,DUPLICIDAD,0,0,0,2023-05-25,2023-08-18,2022-08-23,0,NaN,15786.60,0.0,0.0,186.72,0,15786.60,0.0,0.0,1,0,MEXICO,Weddings,T.O./T.A.,1
13428,493089410601,106,ComplejoRivieraMaya,2023-04-26,2023-05-03,7,AllInclusive,25800,TRSJuniorSuitePPGV,2,2,2,0,0,19700600,1,CD_PALLADIUMTRAVELCLUB_SEMANABENEFICIO,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-04-19,2023-04-27,2022-11-21,0,NaN,1078.00,0.0,0.0,0.00,1,2208.36,0.0,0.0,1,0,ESTADOSUNIDOS,Fixedrates,DIRECTSALES,1
13431,495478110601,106,ComplejoRivieraMaya,2023-04-26,2023-05-03,7,AllInclusive,41900,WSSuiteBeachside,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-04-24,2023-04-27,2022-07-12,0,NaN,1776.32,0.0,0.0,9.80,0,1776.32,0.0,0.0,1,0,URUGUAY,Fixedrates,DIRECTSALES,1
13433,501366109601,96,ComplejoCostaMujeres,2023-03-23,2023-03-26,3,AllInclusive,26500,CMUJuniorSuiteGV,2,2,2,0,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-03-18,2023-03-24,2022-09-26,0,NaN,1075.80,0.0,0.0,8.52,0,1075.80,0.0,0.0,1,0,MEXICO,FixedRates,DIRECTSALES,1
13434,489651009601,96,ComplejoCostaMujeres,2023-04-01,2023-04-08,7,AllInclusive,28100,CMUFSAmbassadorSuiBS,2,3,2,1,0,24258205,1,PTC(DE)_SEMANABENEFICIO,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-03-31,2023-04-02,2023-02-10,0,NaN,1358.00,0.0,0.0,0.00,1,3076.92,0.0,0.0,1,0,ESTADOSUNIDOS,FixedRates,DIRECTSALES,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1294302,518818210601,106,ComplejoRivieraMaya,2023-12-02,2023-12-09,7,AllInclusive,4300,TRSJuniorSuiteGV,2,2,2,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-12-03,2023-12-03,2023-01-22,1528000,PalladiumRewards,2846.76,0.0,0.0,9.80,0,2846.76,0.0,0.0,1,0,CANADA,Loyalty,DIRECTSALES,1
1302321,508311910701,107,ComplejoPuntaCana,2023-12-02,2023-12-09,7,AllInclusive,19600,BAVRooftopJTJS,2,2,2,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-12-03,2023-12-03,2022-11-17,1528000,PalladiumRewards,1922.55,448.0,0.0,0.00,0,1922.55,448.0,0.0,1,0,ESTADOSUNIDOS,Loyalty,DIRECTSALES,1
1303352,532027610601,106,ComplejoRivieraMaya,2023-12-02,2023-12-09,7,AllInclusive,30600,WSRomanceBWbythelake,2,2,2,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-12-03,2023-12-03,2023-01-31,0,NaN,3576.02,0.0,0.0,9.80,0,3576.02,0.0,0.0,1,0,ESTADOSUNIDOS,Package,DIRECTSALES,1
1316604,523221409201,92,GrandPalladiumJamaica&LadyHamiltonResort,2023-04-07,2023-04-09,2,AllInclusive,54900,JAMSupJSPPOV,2,2,2,0,0,19739600,1,HOTELCOLLECT_EXPEDIA,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-03-04,2023-04-08,2023-01-02,0,NaN,1164.48,152.0,0.0,0.00,0,1164.48,152.0,0.0,1,0,ESTADOSUNIDOS,BAR,E-COMMERCE,1
1324006,521113810701,107,ComplejoPuntaCana,2023-12-02,2023-12-09,7,AllInclusive,30800,BAVAmbassadorSuitePOV,2,3,2,1,0,19686200,1,PALLADIUMTRAVELCLUB_SOCIOS,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-12-03,2023-12-03,2022-12-04,0,NaN,993.02,560.0,0.0,0.00,0,993.02,560.0,0.0,1,0,ESPANA,Fixedrates,DIRECTSALES,1

In [98]:
# Imposible
# De momento drop todas
# Pendiente hablar con Palladium para ver si salvamos las de 1 día de diferencia
# Acordado con Palladium dropear sólo las que presentan 2 o más días de antelación
df_Reservas = df_Reservas.drop(df_Reservas.loc[df_Reservas['FECHA_TOMA'] - df_Reservas['FECHA_CANCELACION'] > pd.Timedelta(days=1)].index)

In [99]:
# Rango de fechas de toma

print(max(df_Reservas['FECHA_TOMA']))
print(min(df_Reservas['FECHA_TOMA'])) # Tener en cuenta para df_Moneda

2023-12-31 00:00:00
2018-07-13 00:00:00

#### FIDELIDAD

In [100]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1146450 entries, 1 to 1337937
Data columns (total 44 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1146450 non-null  object
 1   ID_HOTEL           1146450 non-null  object
 2   HOTEL              1146450 non-null  object
 3   LLEGADA            1146450 non-null  datetime64[ns]
 4   SALIDA             1146450 non-null  datetime64[ns]
 5   NOCHES             1146450 non-null  int64
 6   REGIMEN            1146450 non-null  object
 7   ID_TIPO            1146450 non-null  object
 8   TIPO               1146450 non-null  object
 9   USO                1146450 non-null  int64
 10  PAX                1146450 non-null  int64
 11  ADULTOS            1146450 non-null  int64
 12  NENES              1146450 non-null  int64
 13  BEBES              1146450 non-null  int64
 14  ID_CLIENTE         1146450 non-null  object
 15  TIPO_CLIENTE       1146450 non-null  object
 16  CLIENTE            1146450 non-null  object
 17  GRUPO              1146450 non-null  int64
 18  ID_MONEDA          1146450 non-null  object
 19  MONEDA             1146450 non-null  object
 20  STATUS             1146450 non-null  object
 21  MOTIVO             1146450 non-null  object
 22  CHECKIN            1146450 non-null  object
 23  SUPLETORIA         1146450 non-null  int64
 24  CUNAS              1146450 non-null  int64
 25  FECHA_TOMA         1146450 non-null  datetime64[ns]
 26  FECHA_MOD          1146171 non-null  datetime64[ns]
 27  FECHA_CANCELACION  438185 non-null   datetime64[ns]
 28  ID_FIDELIDAD       1146450 non-null  object
 29  FIDELIDAD          154753 non-null   object
 30  VALHAB             1146450 non-null  float64
 31  VALPEN             1146450 non-null  float64
 32  VALSERV            1146450 non-null  float64
 33  VALFIJOS           1146450 non-null  float64
 34  COMERCIALIZADORA   1146450 non-null  int64
 35  CMVALHAB           1146450 non-null  float64
 36  CMVALPEN           1146450 non-null  float64
 37  CMCVALSERV         1146450 non-null  float64
 38  AUTORIZO           1146450 non-null  int64
 39  GRATIS             1146450 non-null  int64
 40  PAIS               1146450 non-null  object
 41  SEGMENTO           1146450 non-null  object
 42  FUENTE_NEGOCIO     1146450 non-null  object
 43  CANCELADA          1146450 non-null  int64
dtypes: datetime64[ns](5), float64(7), int64(13), object(19)
memory usage: 393.6+ MB

In [101]:
# Veamos relación entre ID_FIDELIDAD y FIDELIDAD
print(df_Reservas['ID_FIDELIDAD'].nunique(dropna=False))
print(df_Reservas['FIDELIDAD'].nunique(dropna=False))

4
4

In [102]:
print(df_Reservas['ID_FIDELIDAD'].value_counts(dropna=False))
print(df_Reservas['FIDELIDAD'].value_counts(dropna=False))

ID_FIDELIDAD
0          991697
1528000    151071
1531400      1905
1832800      1777
Name: count, dtype: int64
FIDELIDAD
NaN                 991697
PalladiumRewards    151071
PalladiumConnect      1905
WyndHamRewards        1777
Name: count, dtype: int64

In [103]:
# Para facilitar su posterior trato vamos a modificar los ceros y nans
df_Reservas.loc[df_Reservas['ID_FIDELIDAD'] == 0, 'ID_FIDELIDAD'] = '0000000'
df_Reservas.loc[df_Reservas['FIDELIDAD'].isna(), 'FIDELIDAD'] = 'Ninguna'

In [104]:
# Pinta bien... 1:1?
print('1 ID = N FIDELIDADes')
display(df_Reservas.groupby('ID_FIDELIDAD')['FIDELIDAD'].nunique().sort_values(ascending=False))
print('')
print('1 FIDELIDAD = N IDs')
display(df_Reservas.groupby('FIDELIDAD')['ID_FIDELIDAD'].nunique().sort_values(ascending=False))

1 ID = N FIDELIDADes

ID_FIDELIDAD
1528000    1
1531400    1
1832800    1
0000000    1
Name: FIDELIDAD, dtype: int64

1 FIDELIDAD = N IDs

FIDELIDAD
Ninguna             1
PalladiumConnect    1
PalladiumRewards    1
WyndHamRewards      1
Name: ID_FIDELIDAD, dtype: int64

#### VALORES

In [105]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1146450 entries, 1 to 1337937
Data columns (total 44 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1146450 non-null  object
 1   ID_HOTEL           1146450 non-null  object
 2   HOTEL              1146450 non-null  object
 3   LLEGADA            1146450 non-null  datetime64[ns]
 4   SALIDA             1146450 non-null  datetime64[ns]
 5   NOCHES             1146450 non-null  int64
 6   REGIMEN            1146450 non-null  object
 7   ID_TIPO            1146450 non-null  object
 8   TIPO               1146450 non-null  object
 9   USO                1146450 non-null  int64
 10  PAX                1146450 non-null  int64
 11  ADULTOS            1146450 non-null  int64
 12  NENES              1146450 non-null  int64
 13  BEBES              1146450 non-null  int64
 14  ID_CLIENTE         1146450 non-null  object
 15  TIPO_CLIENTE       1146450 non-null  object
 16  CLIENTE            1146450 non-null  object
 17  GRUPO              1146450 non-null  int64
 18  ID_MONEDA          1146450 non-null  object
 19  MONEDA             1146450 non-null  object
 20  STATUS             1146450 non-null  object
 21  MOTIVO             1146450 non-null  object
 22  CHECKIN            1146450 non-null  object
 23  SUPLETORIA         1146450 non-null  int64
 24  CUNAS              1146450 non-null  int64
 25  FECHA_TOMA         1146450 non-null  datetime64[ns]
 26  FECHA_MOD          1146171 non-null  datetime64[ns]
 27  FECHA_CANCELACION  438185 non-null   datetime64[ns]
 28  ID_FIDELIDAD       1146450 non-null  object
 29  FIDELIDAD          1146450 non-null  object
 30  VALHAB             1146450 non-null  float64
 31  VALPEN             1146450 non-null  float64
 32  VALSERV            1146450 non-null  float64
 33  VALFIJOS           1146450 non-null  float64
 34  COMERCIALIZADORA   1146450 non-null  int64
 35  CMVALHAB           1146450 non-null  float64
 36  CMVALPEN           1146450 non-null  float64
 37  CMCVALSERV         1146450 non-null  float64
 38  AUTORIZO           1146450 non-null  int64
 39  GRATIS             1146450 non-null  int64
 40  PAIS               1146450 non-null  object
 41  SEGMENTO           1146450 non-null  object
 42  FUENTE_NEGOCIO     1146450 non-null  object
 43  CANCELADA          1146450 non-null  int64
dtypes: datetime64[ns](5), float64(7), int64(13), object(19)
memory usage: 393.6+ MB

In [106]:
df_Reservas['COMERCIALIZADORA'].value_counts()

COMERCIALIZADORA
0    640491
1    505959
Name: count, dtype: int64

In [107]:
# Tras hablar con Palladium,
# Si comercializadora 0, valor aplicable = VALHAB + VALPEN + VALSERV + VALFIJOS
# Si comercializadora 1, valor aplicable = CMVALHAB + CMVALPEN + CMCVALSERV
# Comprobemos entonces COMERCIALIZADORA lo primero
df_Reservas['COMERCIALIZADORA'].value_counts(dropna=False)

COMERCIALIZADORA
0    640491
1    505959
Name: count, dtype: int64

In [108]:
# Vigilemos que la suma de valores no da negativo en ningún caso
# Aunque si lo dieran, antes de dropear, miraríamos a ver si atendiendo a comercializadora recobra el sentido
# (es decir si sale negativo pero no aplica, pasamos)

df_Reservas.loc[(df_Reservas['VALHAB'] + df_Reservas['VALPEN'] + df_Reservas['VALSERV'] + df_Reservas['VALFIJOS']) < 0]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,MOTIVO,CHECKIN,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,CANCELADA
146883,492879809601,96,ComplejoCostaMujeres,2022-09-09,2022-09-12,3,AllInclusive,27900,CMUFSJuniorSuiteBS,2,2,2,0,1,19830905,1,ROIBACK(GLOBALOBIS.L.),0,1500,MXN,1,DESCONOCIDO_0,1,0,1,2022-06-27,2022-09-09,NaT,1528000,PalladiumRewards,19951.23,0.0,0.0,-26125.58,0,19951.23,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES,0
816813,604026210701,107,ComplejoPuntaCana,2023-12-16,2023-12-23,7,AllInclusive,44100,PCDeluxePoolside,2,2,2,0,0,19985305,1,AgentConnectPHG,0,700,USD,1,DESCONOCIDO_1,1,0,0,2023-12-11,2023-12-16,NaT,1531400,PalladiumConnect,534.00,448.0,0.0,-982.03,0,534.00,448.0,0.0,1,0,URUGUAY,Package,DIRECTSALES,0
861736,417495709601,96,ComplejoCostaMujeres,2022-03-01,2022-03-08,7,AllInclusive,27500,TRSLoftSuiteJT,2,2,2,0,0,20611405,1,AgentConnectPHGUSA,0,700,USD,3,CLIENTE,0,0,0,2021-06-04,2022-02-04,2022-02-04,1531400,PalladiumConnect,1540.00,0.0,0.0,-3060.26,0,1540.00,0.0,0.0,1,0,ESTADOSUNIDOS,TravelIndustry,DIRECTSALES,1
1069151,473069608301,83,GrandPalladiumImbassaiResort&Spa,2022-06-23,2022-06-26,3,AllInclusive,47700,SSAJuniorSuitePS,2,2,2,0,0,19830905,1,ROIBACK(GLOBALOBIS.L.),0,800,BRL,1,DESCONOCIDO_0,1,0,0,2022-04-02,2022-06-23,NaT,1528000,PalladiumRewards,2745.84,906.0,0.0,-12577.54,0,2745.84,906.0,0.0,1,0,BRASIL,Loyalty,DIRECTSALES,0
1237659,464272409601,96,ComplejoCostaMujeres,2022-02-23,2022-02-24,1,AllInclusive,26500,CMUJuniorSuiteGV,2,2,2,0,1,20341305,1,CALLCENTER,0,1500,MXN,1,DESCONOCIDO_0,1,0,1,2022-02-20,2022-02-23,NaT,1528000,PalladiumRewards,3844.64,0.0,0.0,-7631.61,0,3844.64,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES,0
1299272,454629300601,6,PalladiumVallarta,2022-01-17,2022-01-19,2,AllInclusive,30300,PVRFSJuniorSuiteGV,2,3,3,0,0,20341305,1,CALLCENTER,0,1500,MXN,1,DESCONOCIDO_0,1,0,0,2022-01-04,2022-01-17,NaT,1528000,PalladiumRewards,13126.92,0.0,0.0,-13126.96,0,13126.92,0.0,0.0,1,0,MEXICO,Loyalty,DIRECTSALES,0

In [109]:
# Vemos que ni es de comercializadora, ni es gratis, ni necesariamente está cancelada
# Claramente son errores, dropeamos
df_Reservas = df_Reservas.drop(df_Reservas.loc[(df_Reservas['VALHAB'] + df_Reservas['VALPEN'] + df_Reservas['VALSERV'] + df_Reservas['VALFIJOS']) < 0].index)

In [110]:
# Misma comprobación para COMERCIALIZADORA 1
df_Reservas.loc[(df_Reservas['CMVALHAB'] + df_Reservas['CMVALPEN'] + df_Reservas['CMCVALSERV']) < 0]

,ID_RESERVA,ID_HOTEL,HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,GRUPO,ID_MONEDA,MONEDA,STATUS,MOTIVO,CHECKIN,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,CANCELADA
374343,551650710701,107,ComplejoPuntaCana,2023-06-17,2023-06-21,4,AllInclusive,38800,PCDeluxeGardenView,2,2,2,0,0,20902905,1,CALLCENTER-DE,0,700,USD,3,DESCONOCIDO_0,0,0,0,2023-03-19,2023-06-18,2023-05-19,1528000,PalladiumRewards,181.44,256.0,0.0,0.0,1,-2427.42,256.0,0.0,1,0,ESTADOSUNIDOS,Loyalty,DIRECTSALES,1

In [111]:
# Está cancelada, pero aún así no tiene sentido,
# Por qué voy a cancelar una habitación si me pagan más de 2000€ por disfrutarla?
# Dropeamos

df_Reservas = df_Reservas.drop(index=374343)

#### AUTORIZO

In [112]:
df_Reservas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1146443 entries, 1 to 1337937
Data columns (total 44 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1146443 non-null  object
 1   ID_HOTEL           1146443 non-null  object
 2   HOTEL              1146443 non-null  object
 3   LLEGADA            1146443 non-null  datetime64[ns]
 4   SALIDA             1146443 non-null  datetime64[ns]
 5   NOCHES             1146443 non-null  int64
 6   REGIMEN            1146443 non-null  object
 7   ID_TIPO            1146443 non-null  object
 8   TIPO               1146443 non-null  object
 9   USO                1146443 non-null  int64
 10  PAX                1146443 non-null  int64
 11  ADULTOS            1146443 non-null  int64
 12  NENES              1146443 non-null  int64
 13  BEBES              1146443 non-null  int64
 14  ID_CLIENTE         1146443 non-null  object
 15  TIPO_CLIENTE       1146443 non-null  object
 16  CLIENTE            1146443 non-null  object
 17  GRUPO              1146443 non-null  int64
 18  ID_MONEDA          1146443 non-null  object
 19  MONEDA             1146443 non-null  object
 20  STATUS             1146443 non-null  object
 21  MOTIVO             1146443 non-null  object
 22  CHECKIN            1146443 non-null  object
 23  SUPLETORIA         1146443 non-null  int64
 24  CUNAS              1146443 non-null  int64
 25  FECHA_TOMA         1146443 non-null  datetime64[ns]
 26  FECHA_MOD          1146164 non-null  datetime64[ns]
 27  FECHA_CANCELACION  438183 non-null   datetime64[ns]
 28  ID_FIDELIDAD       1146443 non-null  object
 29  FIDELIDAD          1146443 non-null  object
 30  VALHAB             1146443 non-null  float64
 31  VALPEN             1146443 non-null  float64
 32  VALSERV            1146443 non-null  float64
 33  VALFIJOS           1146443 non-null  float64
 34  COMERCIALIZADORA   1146443 non-null  int64
 35  CMVALHAB           1146443 non-null  float64
 36  CMVALPEN           1146443 non-null  float64
 37  CMCVALSERV         1146443 non-null  float64
 38  AUTORIZO           1146443 non-null  int64
 39  GRATIS             1146443 non-null  int64
 40  PAIS               1146443 non-null  object
 41  SEGMENTO           1146443 non-null  object
 42  FUENTE_NEGOCIO     1146443 non-null  object
 43  CANCELADA          1146443 non-null  int64
dtypes: datetime64[ns](5), float64(7), int64(13), object(19)
memory usage: 393.6+ MB

In [113]:
df_Reservas['AUTORIZO'].value_counts()

AUTORIZO
1    1145659
0        784
Name: count, dtype: int64

In [114]:
# Todo parece ok, seguimos

#### GRATIS

In [115]:
df_Reservas['GRATIS'].value_counts()

GRATIS
0    1145813
1        630
Name: count, dtype: int64

In [116]:
# Todo parece ok, seguimos

#### PAIS

In [117]:
df_Reservas['PAIS'].nunique(dropna=False)

264

In [118]:
df_Reservas['PAIS'].value_counts(dropna=False)

PAIS
ESTADOSUNIDOS                              395764
MEXICO                                     148564
CANADA                                     103409
BRASIL                                      90637
SINPAIS                                     74946
ARGENTINA                                   69929
REPUBLICADOMINICANA                         51171
ESPANA                                      37219
REINOUNIDO                                  33586
ALEMANIA                                    19183
JAMAICA                                     17385
URUGUAY                                     13830
DOMINICA                                    10874
COLOMBIA                                    10761
PERU                                         9666
CHILE                                        8386
FRANCIA                                      3353
COREA                                        3073
SUIZA                                        2485
ITALIA                                       2442
POLONIA                                      2114
PAISESBAJOS                                  1941
BOLIVIA                                      1930
PARAGUAY                                     1908
PORTUGAL                                     1803
PUERTORICO                                   1625
RUSIA                                        1497
AUSTRIA                                      1495
CHINA                                        1416
ECUADOR                                      1339
EMIRATOSARABESUNIDOS                         1205
INDIA                                        1163
BELGICA                                      1129
AFGANISTAN                                   1030
GUATEMALA                                     894
RUMANIA                                       825
VENEZUELA                                     714
IRLANDA                                       682
COSTARICA                                     679
HAITI                                         645
COREADELSUR                                   644
PANAMA                                        620
SUECIA                                        619
HUNGRIA                                       609
UCRANIA                                       517
FEDERACIONDERUSIA                             492
ISRAEL                                        467
TURQUIA                                       449
ISLASULTRAMARINASMENORESDEESTADOSUNIDOS       445
AUSTRALIA                                     428
CUBA                                          406
REPUBLICACHECA                                379
ELSALVADOR                                    345
ESLOVAQUIA                                    313
HONDURAS                                      280
ALBANIA                                       272
FILIPINAS                                     224
BULGARIA                                      215
NIGERIA                                       208
MARRUECOS                                     198
ANDORRA                                       181
TRINIDADYTOBAGO                               179
JAPON                                         174
LITUANIA                                      173
DINAMARCA                                     167
NORUEGA                                       167
CHIPRE                                        147
BERMUDAS                                      141
LUXEMBURGO                                    140
BAHAMAS                                       125
GUAYANA                                       101
ESLOVENIA                                      95
SERBIA                                         95
NICARAGUA                                      93
CROACIA                                        87
ESTONIA                                        86
ANGOLA                                         84
SUDAFRICA                                      84
SINGAPUR                                       80
TAIWAN                                         79
IRAN                                           78
NUEVAZELANDA                                   75
LETONIA                                        71
GEORGIA                                        71
BIELORRUSIA                                    71
GRECIA                                         71
FINLANDIA                                      68
CURAZAO                                        63
ISLASULTRAMARINASMENORESDE                     60
VIETNAM                                        58
ANGUILLA                                       57
SANTALUCIA                                     56
JORDANIA                                       55
ISLASCAIMAN                                    55
KAZAJISTAN                                     53
ANTIGUAYBARBUDA                                51
TANZANIA                                       50
BELICE                                         50
ARUBA                                          49
MARTINICA                                      48
ISLASTURCASYCAICOS                             46
BARBADOS                                       42
KENIA                                          41
MACEDONIA                                      41
MONTENEGRO                                     41
UZBEKISTAN                                     39
ARABIASAUDI                                    38
MACAO                                          38
BOSNIAYHERCEGOVINA                             38
ARMENIA                                        37
ANTARTIDA                                      36
LIBANO                                         34
EGIPTO                                         34
ARGELIA                                        34
REPUBLICADEKOSOVO                              33
TAILANDIA                                      32
PAKISTAN                                       31
ISLASVIRGENESBRITANICAS                        31
CAMERUN                                        31
HONGKONG                                       31
SANCRISTOBALYNIEVES                            30
ISLADENAVIDAD                                  29
REPUBLICADEMOLDAVIA                            28
TUNEZ                                          27
GIBRALTAR                                      27
ANGUILA                                        25
MICRONESIA                                     25
MALTA                                          24
MALASIA                                        24
ISLASVIRGENESDELOSESTADOSUNIDOS                23
BANGLADES                                      22
ISLANDIA                                       21
INDONESIA                                      21
KUWAIT                                         21
SUAZILANDIA                                    20
GUAYANAFRANCESA                                19
QATAR                                          19
NETHERLANDSANTILLES                            19
NEPAL                                          18
REPDEMOCRATICADELCONGO                         18
CABOVERDE                                      18
LIECHTENSTEIN                                  18
GUADALUPESAINTMARTINYSAINTBARTHELEMY           18
REUNION                                        18
LIBERIA                                        17
SRILANKA                                       17
GRANADA                                        17
SIRIA                                          17
GHANA                                          17
SANVICENTEYLASGRANADINAS                       17
AZERBAIYAN                                     17
ETIOPIA                                        16
BAHREIN                                        16
SENEGAL                                        15
REPUBLICACENTROAFRICANA                        15
SANMARTIN                                      15
ISLASVIRGENESDEEEUU                            14
JERSEY                                         14
POLINESIAFRANCES                               14
REPUBLICADEMAURICIO                            13
SOMALIA                                        13
UGANDA                                         13
ZIMBABUE                                       12
COSTADEMARFIL                                  11
GUAM                                           11
SINTMAARTEN                                    11
GUADALUPE,SAINTMARTINYSAINTBARTHELEMY          11
SURINAM                                        10
CHAD                                           10
BOTSWANA                                       10
MYANMAR                                         9
MONGOLIA                                        9
SAMOAAMERICANA                                  9
REP.DEMOCRATICADELCONGO                         8
REPUBLICADEMOZAMBIQUE                           8
IRAQ                                            8
BRUNEIDARUSSALAM                                7
ARABIASAUDITA                                   7
ISLASVIRGENESDEEE.UU                            7
ISLASALAND                                      7
SANMARINO                                       6
KIRGUISTAN                                      6
MONACO                                          6
NIGER                                           6
MAURITANIA                                      6
SIERRALEONA                                     5
GUINEA                                          5
GUADALUPE                                       5
ISLADELHOMBRE                                   5
CAMBOYA                                         5
BUTAN                                           5
BURKINAFASO                                     5
ISLASBERMUDAS                                   5
OMAN                                            5
LAOS                                            4
MALAWI                                          4
VANUATU                                         4
PALESTINA                                       4
NAMIBIA                                         4
BURUNDI                                         4
MADAGASCAR                                      4
CIUDADDELVATICANO                               4
ZAMBIA                                          4
TAYIKISTAN                                      4
MAYOTTE                                         4
ERITREA                                         3
SANPEDROYMIQUELON                               3
ARABESAHARAUI(SAHARAOCCIDEN                     3
SUDAN                                           3
GABON                                           3
SAMOA                                           3
MAURICIO                                        3
ISLASFEROE                                      3
DJIBOUTI                                        3
FIYI                                            3
MALI                                            3
BENIN                                           3
LESOTO                                          3
YIBUTI                                          3
TUVALU                                          3
LIBIA                                           3
BOTSUANA                                        2
TURKMENISTAN                                    2
NIUE                                            2
SWAZILANDIA                                     2
GUYANA                                          2
GUINEAECUATORIAL                                2
SEYCHELLES                                      2
MALDIVAS                                        2
TOGO                                            2
TOKELAU                                         2
NUEVACALEDONIA                                  2
TONGA                                           2
IR                                              2
REUNIONYMAYOTTE                                 2
GUERNSEY                                        2
RUANDA                                          2
BANGLADESH                                      1
BRUNEI                                          1
IRAK                                            1
ISLASSALOMON                                    1
ISLASHEARDYMCDONALD                             1
SUDANDELSUR                                     1
TERRITORIOSFRANCESESDELSUR                      1
ISLASTURCOSYCAICOS                              1
WALLISYFUTUNA                                   1
BHUTAN                                          1
REPUBLICADELCONGO                               1
GROENLANDIA                                     1
ISLASMALVINAS                                   1
COREADELNORTE                                   1
ANTILLASNEERLANDESAS                            1
SVALBARDYJANMAYEN                               1
GUINEA-BISSAU                                   1
COMORAS                                         1
REPUBLICADEMOCRATICADELCONGO                    1
ISLASMARIANASDELNORTE                           1
PAPUANUEVAGUINEA                                1
TERRITORIOBRITANICODELOCEANOINDICO              1
MOLDAVIA                                        1
CONGO(BRAZZAVILLE)                              1
NAURU                                           1
KIRIBATI                                        1
TERRITORIOBRITANICODELOCEAN                     1
Name: count, dtype: int64

In [119]:
# Visualizamos como df para facilitar
# Veamos si hay países con algún caracter cambiado ordeando por a-z
# Poco más se puede hacer, pero por ahora parece ok
df_conteo_Reservas = df_Reservas['PAIS'].value_counts().to_frame().reset_index()
df_conteo_Reservas.sort_values('PAIS', ascending=True)

                                        PAIS   count
33                                AFGANISTAN    1030
55                                   ALBANIA     272
9                                   ALEMANIA   19183
60                                   ANDORRA     181
76                                    ANGOLA      84
125                                  ANGUILA      25
90                                  ANGUILLA      57
110                                ANTARTIDA      36
95                           ANTIGUAYBARBUDA      51
251                     ANTILLASNEERLANDESAS       1
207              ARABESAHARAUI(SAHARAOCCIDEN       3
106                              ARABIASAUDI      38
177                            ARABIASAUDITA       7
113                                  ARGELIA      34
5                                  ARGENTINA   69929
109                                  ARMENIA      37
98                                     ARUBA      49
49                                 AUSTRALIA     428
27                                   AUSTRIA    1495
150                               AZERBAIYAN      17
69                                   BAHAMAS     125
152                                  BAHREIN      16
130                                BANGLADES      22
237                               BANGLADESH       1
101                                 BARBADOS      42
32                                   BELGICA    1129
97                                    BELICE      50
216                                    BENIN       3
67                                  BERMUDAS     141
246                                   BHUTAN       1
84                               BIELORRUSIA      71
22                                   BOLIVIA    1930
108                       BOSNIAYHERCEGOVINA      38
221                                 BOTSUANA       2
169                                 BOTSWANA      10
3                                     BRASIL   90637
238                                   BRUNEI       1
176                         BRUNEIDARUSSALAM       7
57                                  BULGARIA     215
191                              BURKINAFASO       5
199                                  BURUNDI       4
190                                    BUTAN       5
140                                CABOVERDE      18
189                                  CAMBOYA       5
118                                  CAMERUN      31
2                                     CANADA  103409
168                                     CHAD      10
15                                     CHILE    8386
28                                     CHINA    1416
66                                    CHIPRE     147
201                        CIUDADDELVATICANO       4
13                                  COLOMBIA   10761
254                                  COMORAS       1
260                       CONGO(BRAZZAVILLE)       1
17                                     COREA    3073
250                            COREADELNORTE       1
40                               COREADELSUR     644
163                            COSTADEMARFIL      11
38                                 COSTARICA     679
74                                   CROACIA      87
50                                      CUBA     406
87                                   CURAZAO      63
64                                 DINAMARCA     167
213                                 DJIBOUTI       3
12                                  DOMINICA   10874
29                                   ECUADOR    1339
112                                   EGIPTO      34
52                                ELSALVADOR     345
30                      EMIRATOSARABESUNIDOS    1205
205                                  ERITREA       3
53                                ESLOVAQUIA     313
71                                 ESLOVENIA      95
7                                     ESPANA   37219
0                              ESTADOSUNIDOS  395764
75                                   ESTONIA      86
151                                  ETIOPIA      16
45                         FEDERACIONDERUSIA     492
56                                 FILIPINAS     224
86                                 FINLANDIA      68
214                                     FIYI       3
16                                   FRANCIA    3353
209                                    GABON       3
83                                   GEORGIA      71
148                                    GHANA      17
124                                GIBRALTAR      27
146                                  GRANADA      17
85                                    GRECIA      71
248                              GROENLANDIA       1
187                                GUADALUPE       5
166    GUADALUPE,SAINTMARTINYSAINTBARTHELEMY      11
142     GUADALUPESAINTMARTINYSAINTBARTHELEMY      18
164                                     GUAM      11
34                                 GUATEMALA     894
70                                   GUAYANA     101
135                          GUAYANAFRANCESA      19
235                                 GUERNSEY       2
186                                   GUINEA       5
253                            GUINEA-BISSAU       1
226                         GUINEAECUATORIAL       2
225                                   GUYANA       2
39                                     HAITI     645
54                                  HONDURAS     280
119                                 HONGKONG      31
43                                   HUNGRIA     609
31                                     INDIA    1163
132                                INDONESIA      21
233                                       IR       2
239                                     IRAK       1
80                                      IRAN      78
175                                     IRAQ       8
37                                   IRLANDA     682
188                            ISLADELHOMBRE       5
121                            ISLADENAVIDAD      29
131                                 ISLANDIA      21
179                               ISLASALAND       7
192                            ISLASBERMUDAS       5
93                               ISLASCAIMAN      55
212                               ISLASFEROE       3
241                      ISLASHEARDYMCDONALD       1
249                            ISLASMALVINAS       1
256                    ISLASMARIANASDELNORTE       1
240                             ISLASSALOMON       1
100                       ISLASTURCASYCAICOS      46
244                       ISLASTURCOSYCAICOS       1
88                ISLASULTRAMARINASMENORESDE      60
48   ISLASULTRAMARINASMENORESDEESTADOSUNIDOS     445
117                  ISLASVIRGENESBRITANICAS      31
178                     ISLASVIRGENESDEEE.UU       7
156                      ISLASVIRGENESDEEEUU      14
129          ISLASVIRGENESDELOSESTADOSUNIDOS      23
46                                    ISRAEL     467
19                                    ITALIA    2442
10                                   JAMAICA   17385
62                                     JAPON     174
157                                   JERSEY      14
92                                  JORDANIA      55
94                                KAZAJISTAN      53
102                                    KENIA      41
181                               KIRGUISTAN       6
262                                 KIRIBATI       1
133                                   KUWAIT      21
194                                     LAOS       4
217                                   LESOTO       3
82                                   LETONIA      71
111                                   LIBANO      34
144                                  LIBERIA      17
220                                    LIBIA       3
141                            LIECHTENSTEIN      18
63                                  LITUANIA     173
68                                LUXEMBURGO     140
107                                    MACAO      38
103                                MACEDONIA      41
200                               MADAGASCAR       4
128                                  MALASIA      24
195                                   MALAWI       4
228                                 MALDIVAS       2
215                                     MALI       3
127                                    MALTA      24
59                                 MARRUECOS     198
99                                 MARTINICA      48
211                                 MAURICIO       3
184                               MAURITANIA       6
204                                  MAYOTTE       4
1                                     MEXICO  148564
126                               MICRONESIA      25
259                                 MOLDAVIA       1
182                                   MONACO       6
171                                 MONGOLIA       9
104                               MONTENEGRO      41
170                                  MYANMAR       9
198                                  NAMIBIA       4
261                                    NAURU       1
138                                    NEPAL      18
137                      NETHERLANDSANTILLES      19
73                                 NICARAGUA      93
183                                    NIGER       6
58                                   NIGERIA     208
223                                     NIUE       2
65                                   NORUEGA     167
231                           NUEVACALEDONIA       2
81                              NUEVAZELANDA      75
193                                     OMAN       5
21                               PAISESBAJOS    1941
116                                 PAKISTAN      31
197                                PALESTINA       4
41                                    PANAMA     620
257                         PAPUANUEVAGUINEA       1
23                                  PARAGUAY    1908
14                                      PERU    9666
158                         POLINESIAFRANCES      14
20                                   POLONIA    2114
24                                  PORTUGAL    1803
25                                PUERTORICO    1625
136                                    QATAR      19
8                                 REINOUNIDO   33586
173                  REP.DEMOCRATICADELCONGO       8
139                   REPDEMOCRATICADELCONGO      18
154                  REPUBLICACENTROAFRICANA      15
51                            REPUBLICACHECA     379
114                        REPUBLICADEKOSOVO      33
247                        REPUBLICADELCONGO       1
159                      REPUBLICADEMAURICIO      13
255             REPUBLICADEMOCRATICADELCONGO       1
122                      REPUBLICADEMOLDAVIA      28
174                    REPUBLICADEMOZAMBIQUE       8
6                        REPUBLICADOMINICANA   51171
143                                  REUNION      18
234                          REUNIONYMAYOTTE       2
236                                   RUANDA       2
35                                   RUMANIA     825
26                                     RUSIA    1497
210                                    SAMOA       3
172                           SAMOAAMERICANA       9
120                      SANCRISTOBALYNIEVES      30
180                                SANMARINO       6
155                                SANMARTIN      15
206                        SANPEDROYMIQUELON       3
91                                SANTALUCIA      56
149                 SANVICENTEYLASGRANADINAS      17
153                                  SENEGAL      15
72                                    SERBIA      95
227                               SEYCHELLES       2
185                              SIERRALEONA       5
78                                  SINGAPUR      80
4                                    SINPAIS   74946
165                              SINTMAARTEN      11
147                                    SIRIA      17
160                                  SOMALIA      13
145                                 SRILANKA      17
134                              SUAZILANDIA      20
77                                 SUDAFRICA      84
208                                    SUDAN       3
242                              SUDANDELSUR       1
42                                    SUECIA     619
18                                     SUIZA    2485
167                                  SURINAM      10
252                        SVALBARDYJANMAYEN       1
224                              SWAZILANDIA       2
115                                TAILANDIA      32
79                                    TAIWAN      79
96                                  TANZANIA      50
203                               TAYIKISTAN       4
263              TERRITORIOBRITANICODELOCEAN       1
258       TERRITORIOBRITANICODELOCEANOINDICO       1
243               TERRITORIOSFRANCESESDELSUR       1
229                                     TOGO       2
230                                  TOKELAU       2
232                                    TONGA       2
61                           TRINIDADYTOBAGO     179
123                                    TUNEZ      27
222                             TURKMENISTAN       2
47                                   TURQUIA     449
219                                   TUVALU       3
44                                   UCRANIA     517
161                                   UGANDA      13
11                                   URUGUAY   13830
105                               UZBEKISTAN      39
196                                  VANUATU       4
36                                 VENEZUELA     714
89                                   VIETNAM      58
245                            WALLISYFUTUNA       1
218                                   YIBUTI       3
202                                   ZAMBIA       4
162                                 ZIMBABUE      12

In [120]:
df_conteo_Reservas.head()

            PAIS   count
0  ESTADOSUNIDOS  395764
1         MEXICO  148564
2         CANADA  103409
3         BRASIL   90637
4        SINPAIS   74946

In [121]:
# Fusionar

# ANGUILA	25
# ANGUILLA	57
df_Reservas.loc[df_Reservas['PAIS'] == 'ANGUILA', 'PAIS'] = 'ANGUILLA'

# BANGLADES	22
# BANGLADESH	1
df_Reservas.loc[df_Reservas['PAIS'] == 'BANGLADESH', 'PAIS'] = 'BANGLADES'

# BHUTAN
# BUTAN
df_Reservas.loc[df_Reservas['PAIS'] == 'BHUTAN', 'PAIS'] = 'BUTAN'

# BRUNEI	1
# BRUNEIDARUSSALAM	7
df_Reservas.loc[df_Reservas['PAIS'] == 'BRUNEIDARUSSALAM', 'PAIS'] = 'BRUNEI'

# COREA	3066
# COREADELSUR	630
df_Reservas.loc[df_Reservas['PAIS'] == 'COREA', 'PAIS'] = 'COREADELSUR'

# FEDERACIONDERUSIA	487
# RUSIA	1487
df_Reservas.loc[df_Reservas['PAIS'] == 'FEDERACIONDERUSIA', 'PAIS'] = 'RUSIA'

# GUADALUPE	5
# GUADALUPE,SAINTMARTINYSAINTBARTHELEMY	11
# GUADALUPESAINTMARTINYSAINTBARTHELEMY 17
# SANMARTIN 15
df_Reservas.loc[(df_Reservas['PAIS'] == 'GUADALUPE,SAINTMARTINYSAINTBARTHELEMY') | (df_Reservas['PAIS'] == 'GUADALUPESAINTMARTINYSAINTBARTHELEMY') | (df_Reservas['PAIS'] == 'SANMARTIN'), 'PAIS'] = 'GUADALUPE'

# IRAK
# IRAQ
df_Reservas.loc[df_Reservas['PAIS'] == 'IRAQ', 'PAIS'] = 'IRAK'

# ISLASTURCASYCAICOS	46
# ISLASTURCOSYCAICOS	1
df_Reservas.loc[df_Reservas['PAIS'] == 'ISLASTURCOSYCAICOS', 'PAIS'] = 'ISLASTURCASYCAICOS'

# ISLASULTRAMARINASMENORESDE	60
# ISLASULTRAMARINASMENORESDEESTADOSUNIDOS	444
df_Reservas.loc[df_Reservas['PAIS'] == 'ISLASULTRAMARINASMENORESDE', 'PAIS'] = 'ISLASULTRAMARINASMENORESDEESTADOSUNIDOS'

# ISLASVIRGENESDEEE.UU	7
# ISLASVIRGENESDEEEUU	14
# ISLASVIRGENESDELOSESTADOSUNIDOS	23
df_Reservas.loc[(df_Reservas['PAIS'] == 'ISLASVIRGENESDEEE.UU') | (df_Reservas['PAIS'] == 'ISLASVIRGENESDEEEUU'), 'PAIS'] = 'ISLASVIRGENESDELOSESTADOSUNIDOS'

# MAURICIO
# REPUBLICADEMAURICIO
df_Reservas.loc[df_Reservas['PAIS'] == 'REPUBLICADEMAURICIO', 'PAIS'] = 'MAURICIO'

# MOLDAVIA
# REPUBLICADEMOLDAVIA
df_Reservas.loc[df_Reservas['PAIS'] == 'REPUBLICADEMOLDAVIA', 'PAIS'] = 'MOLDAVIA'


# REP.DEMOCRATICADELCONGO	8
# REPDEMOCRATICADELCONGO	18
df_Reservas.loc[df_Reservas['PAIS'] == 'REP.DEMOCRATICADELCONGO', 'PAIS'] = 'REPDEMOCRATICADELCONGO'

# REPUBLICADELCONGO	1
# CONGO(BRAZZAVILLE)	1
df_Reservas.loc[df_Reservas['PAIS'] == 'CONGO(BRAZZAVILLE)', 'PAIS'] = 'REPUBLICADELCONGO'

# MAYOTTE	4
# REUNION	18
# REUNIONYMAYOTTE	2
df_Reservas.loc[(df_Reservas['PAIS'] == 'MAYOTTE') | (df_Reservas['PAIS'] == 'REUNION'), 'PAIS'] = 'REUNIONYMAYOTTE'

# SUAZILANDIA	20
# SWAZILANDIA	2
df_Reservas.loc[df_Reservas['PAIS'] == 'SWAZILANDIA', 'PAIS'] = 'SUAZILANDIA'

# DJIBOUTI	3
# YIBUTI	3
df_Reservas.loc[df_Reservas['PAIS'] == 'DJIBOUTI', 'PAIS'] = 'YIBUTI'

# Se observan muchos territorios que no son países, pero se mantendrán igualmente por si generasen insights valiosos

In [122]:
df_Reservas['PAIS'].nunique(dropna=False)

242

In [123]:
# A Dropear

# IR, No hay forma de averiguarlo, drop
df_Reservas = df_Reservas.loc[df_Reservas['PAIS'] != 'IR']

In [124]:
df_Reservas['PAIS'].nunique(dropna=False)

241

In [125]:
df_conteo_Reservas = df_Reservas.copy()
df_conteo_Reservas = df_conteo_Reservas['PAIS'].value_counts().to_frame().reset_index()

In [126]:
# Filtro para fusionar países con pocas reservas,
# Ejemplo de lo que podría pasar si no: Xlandia tiene 1 reserva, está cancelada, el modelo interpretaría que el 100% de las reservas de Xlandia se cancelaron
# Mínimas reservas por país para considerarlo país independiente:
min_res = 3

paises_minoritarios = df_conteo_Reservas.loc[df_conteo_Reservas['count'] < min_res, 'PAIS'].tolist()
# También puedo agrupar todos los que tengan menos de X en "minoritarios"

# O dividir el dataset en cuartiles, continente... vamos explorando

In [127]:
paises_minoritarios

['TOGO',
 'GUINEAECUATORIAL',
 'GUYANA',
 'SEYCHELLES',
 'TOKELAU',
 'REPUBLICADELCONGO',
 'MALDIVAS',
 'TONGA',
 'RUANDA',
 'NIUE',
 'TURKMENISTAN',
 'GUERNSEY',
 'NUEVACALEDONIA',
 'BOTSUANA',
 'GROENLANDIA',
 'COREADELNORTE',
 'ISLASMALVINAS',
 'SVALBARDYJANMAYEN',
 'GUINEA-BISSAU',
 'ANTILLASNEERLANDESAS',
 'TERRITORIOBRITANICODELOCEANOINDICO',
 'COMORAS',
 'PAPUANUEVAGUINEA',
 'ISLASMARIANASDELNORTE',
 'REPUBLICADEMOCRATICADELCONGO',
 'SUDANDELSUR',
 'ISLASSALOMON',
 'WALLISYFUTUNA',
 'TERRITORIOSFRANCESESDELSUR',
 'ISLASHEARDYMCDONALD',
 'NAURU',
 'KIRIBATI',
 'TERRITORIOBRITANICODELOCEAN']

In [128]:
# Ahora otorgo a todos ellos el nombre de 'MINORITARIOS'
df_Reservas.loc[df_Reservas['PAIS'].isin(paises_minoritarios), 'PAIS'] = 'MINORITARIOS'

In [129]:
print(f"Países después del corte = {df_Reservas['PAIS'].nunique()}")

Países después del corte = 209

#### SEGMENTO

In [130]:
df_Reservas['SEGMENTO'].value_counts(dropna=False)

SEGMENTO
FixedRates        511261
BAR               240138
Loyalty           120692
Package            91814
GroupLeisure       74505
Weddings           51427
Fixedrates         50538
MICE                3638
Opaque              1454
Complimentary        620
Miscellaneous        262
TravelIndustry        92
Name: count, dtype: int64

In [131]:
# Todo ok

#### FUENTE_NEGOCIO

In [132]:
df_Reservas['FUENTE_NEGOCIO'].value_counts(dropna=False)

FUENTE_NEGOCIO
T.O./T.A.      500667
E-COMMERCE     306544
DIRECTSALES    284483
CORPORATE       53749
OTHERS            998
Name: count, dtype: int64

In [133]:
# Todo ok

#### Exportación del dataset limpio

In [134]:
df_Reservas.to_csv(r'D:\DEV\Python\00_TFM_PALLADIUM\02_DATASETS_GENERADOS\Reservas_22_23_Limpio.csv', index=False)